export const countriesAndStates = [
  {
    label: "Nigeria",
    value: "Nigeria",
    country: "Nigeria",
    states: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
      "Federal Capital Territory",
    ],
  },
  {
    label: "Afghanistan",
    value: "Afghanistan",
    country: "Afghanistan",
    states: [
      "Badakhshan",
      "Badghis",
      "Baghlan",
      "Balkh",
      "Bamyan",
      "Daykundi",
      "Farah",
      "Faryab",
      "Ghazni",
      "Ghor",
      "Helmand",
      "Herat",
      "Jowzjan",
      "Kabul",
      "Kandahar",
      "Kapisa",
      "Khost",
      "Kunar",
      "Kunduz",
      "Laghman",
      "Logar",
      "Nangarhar",
      "Nimroz",
      "Nuristan",
      "Paktia",
      "Paktika",
      "Panjshir",
      "Parwan",
      "Samangan",
      "Sar-e Pol",
      "Takhar",
      "Urozgan",
      "Wardak",
      "Zabul",
    ],
  },
  {
    label: "Albania",
    value: "Albania",
    country: "Albania",
    states: [
      "Berat",
      "Dibër",
      "Durrës",
      "Elbasan",
      "Fier",
      "Gjirokastër",
      "Korçë",
      "Kukës",
      "Lezhë",
      "Shkodër",
      "Tiranë",
      "Vlorë",
    ],
  },
  {
    label: "Algeria",
    value: "Algeria",
    country: "Algeria",
    states: [
      "Adrar",
      "Aïn Defla",
      "Aïn Témouchent",
      "Algiers",
      "Annaba",
      "Batna",
      "Béchar",
      "Béjaïa",
      "Biskra",
      "Blida",
      "Bordj Bou Arréridj",
      "Bouïra",
      "Boumerdès",
      "Chlef",
      "Constantine",
      "Djelfa",
      "El Bayadh",
      "El Oued",
      "El Tarf",
      "Ghardaïa",
      "Guelma",
      "Illizi",
      "Jijel",
      "Khenchela",
      "Laghouat",
      "M'Sila",
      "Mascara",
      "Médéa",
      "Mila",
      "Mostaganem",
      "Naama",
      "Oran",
      "Ouargla",
      "Oum El Bouaghi",
      "Relizane",
      "Saïda",
      "Sétif",
      "Sidi Bel Abbès",
      "Skikda",
      "Souk Ahras",
      "Tamanrasset",
      "Tébessa",
      "Tiaret",
      "Tindouf",
      "Tipaza",
      "Tissemsilt",
      "Tizi Ouzou",
      "Tlemcen",
    ],
  },
  {
    label: "Andorra",
    value: "Andorra",
    country: "Andorra",
    states: [
      "Andorra la Vella",
      "Canillo",
      "Encamp",
      "Escaldes-Engordany",
      "La Massana",
      "Ordino",
      "Sant Julià de Lòria",
    ],
  },
  {
    label: "Angola",
    value: "Angola",
    country: "Angola",
    states: [
      "Bengo",
      "Benguela",
      "Bié",
      "Cabinda",
      "Cuando Cubango",
      "Cuanza Norte",
      "Cuanza Sul",
      "Cunene",
      "Huambo",
      "Huíla",
      "Luanda",
      "Lunda Norte",
      "Lunda Sul",
      "Malanje",
      "Moxico",
      "Namibe",
      "Uíge",
      "Zaire",
    ],
  },
  {
    label: "Antigua and Barbuda",
    value: "Antigua and Barbuda",
    country: "Antigua and Barbuda",
    states: [
      "Barbuda",
      "Redonda",
      "Saint George",
      "Saint John",
      "Saint Mary",
      "Saint Paul",
      "Saint Peter",
      "Saint Philip",
    ],
  },
  {
    label: "Argentina",
    value: "Argentina",
    country: "Argentina",
    states: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  {
    label: "Armenia",
    value: "Armenia",
    country: "Armenia",
    states: [
      "Aragatsotn",
      "Ararat",
      "Armavir",
      "Gegharkunik",
      "Kotayk",
      "Lori",
      "Shirak",
      "Syunik",
      "Tavush",
      "Vayots Dzor",
      "Yerevan",
    ],
  },
  {
    label: "Australia",
    value: "Australia",
    country: "Australia",
    states: [
      "Australian Capital Territory",
      "New South Wales",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
    ],
  },
  {
    label: "Austria",
    value: "Austria",
    country: "Austria",
    states: [
      "Burgenland",
      "Carinthia",
      "Lower Austria",
      "Salzburg",
      "Styria",
      "Tyrol",
      "Upper Austria",
      "Vienna",
      "Vorarlberg",
    ],
  },
  {
    label: "Azerbaijan",
    value: "Azerbaijan",
    country: "Azerbaijan",
    states: [
      "Absheron",
      "Agstafa",
      "Agsu",
      "Astara",
      "Balakan",
      "Barda",
      "Beylagan",
      "Bilasuvar",
      "Dashkasan",
      "Fizuli",
      "Ganja",
      "Goranboy",
      "Goychay",
      "Goygol",
      "Hajigabul",
      "Imishli",
      "Ismailli",
      "Jabrayil",
      "Jalilabad",
      "Kalbajar",
      "Kangarli",
      "Khachmaz",
      "Khizi",
      "Khojali",
      "Kurdamir",
      "Lachin",
      "Lankaran",
      "Lerik",
      "Masally",
      "Mingachevir",
      "Nakhchivan",
      "Neftchala",
      "Oghuz",
      "Qabala",
      "Qakh",
      "Qazakh",
      "Quba",
      "Qubadli",
      "Qusar",
      "Saatly",
      "Sabirabad",
      "Shaki",
      "Shamakhi",
      "Shamkir",
      "Shirvan",
      "Siazan",
      "Sumqayit",
      "Tartar",
      "Tovuz",
      "Ujar",
      "Yardymli",
      "Yevlakh",
      "Zangilan",
      "Zaqatala",
      "Zardab",
    ],
  },
  {
    label: "Bahamas",
    value: "Bahamas",
    country: "Bahamas",
    states: [
      "Acklins",
      "Berry Islands",
      "Bimini",
      "Black Point",
      "Cat Island",
      "Central Abaco",
      "Central Andros",
      "Central Eleuthera",
      "City of Freeport",
      "Crooked Island and Long Cay",
      "East Grand Bahama",
      "Exuma",
      "Grand Cay",
      "Harbour Island",
      "Hope Town",
      "Inagua",
      "Long Island",
      "Mangrove Cay",
      "Mayaguana",
      "Moore's Island",
      "North Abaco",
      "North Andros",
      "North Eleuthera",
      "Ragged Island",
      "Rum Cay",
      "San Salvador",
      "South Abaco",
      "South Andros",
      "South Eleuthera",
      "Spanish Wells",
      "West Grand Bahama",
    ],
  },
  {
    label: "Bahrain",
    value: "Bahrain",
    country: "Bahrain",
    states: [
      "Capital Governorate",
      "Central Governorate",
      "Muharraq Governorate",
      "Northern Governorate",
      "Southern Governorate",
    ],
  },
  {
    label: "Bangladesh",
    value: "Bangladesh",
    country: "Bangladesh",
    states: [
      "Barisal Division",
      "Chittagong Division",
      "Dhaka Division",
      "Khulna Division",
      "Mymensingh Division",
      "Rajshahi Division",
      "Rangpur Division",
      "Sylhet Division",
    ],
  },
  {
    label: "Barbados",
    value: "Barbados",
    country: "Barbados",
    states: [
      "Christ Church",
      "Saint Andrew",
      "Saint George",
      "Saint James",
      "Saint John",
      "Saint Joseph",
      "Saint Lucy",
      "Saint Michael",
      "Saint Peter",
      "Saint Philip",
      "Saint Thomas",
    ],
  },
  {
    label: "Belarus",
    value: "Belarus",
    country: "Belarus",
    states: [
      "Brest Region",
      "Gomel Region",
      "Grodno Region",
      "Minsk",
      "Minsk Region",
      "Mogilev Region",
      "Vitebsk Region",
    ],
  },
  {
    label: "Belgium",
    value: "Belgium",
    country: "Belgium",
    states: [
      "Antwerp",
      "Brussels-Capital Region",
      "East Flanders",
      "Flemish Brabant",
      "Hainaut",
      "Liège",
      "Limburg",
      "Luxembourg",
      "Namur",
      "Walloon Brabant",
      "West Flanders",
    ],
  },
  {
    label: "Belize",
    value: "Belize",
    country: "Belize",
    states: [
      "Belize",
      "Cayo",
      "Corozal",
      "Orange Walk",
      "Stann Creek",
      "Toledo",
    ],
  },
  {
    label: "Benin",
    value: "Benin",
    country: "Benin",
    states: [
      "Alibori",
      "Atakora",
      "Atlantique",
      "Borgou",
      "Collines",
      "Donga",
      "Kouffo",
      "Littoral",
      "Mono",
      "Ouémé",
      "Plateau",
      "Zou",
    ],
  },
  {
    label: "Bhutan",
    value: "Bhutan",
    country: "Bhutan",
    states: [
      "Bumthang",
      "Chukha",
      "Dagana",
      "Gasa",
      "Haa",
      "Lhuntse",
      "Mongar",
      "Paro",
      "Pemagatshel",
      "Punakha",
      "Samdrup Jongkhar",
      "Samtse",
      "Sarpang",
      "Thimphu",
      "Trashigang",
      "Trongsa",
      "Tsirang",
      "Wangdue Phodrang",
      "Zhemgang",
    ],
  },
  {
    label: "Bolivia",
    value: "Bolivia",
    country: "Bolivia",
    states: [
      "Beni",
      "Chuquisaca",
      "Cochabamba",
      "La Paz",
      "Oruro",
      "Pando",
      "Potosí",
      "Santa Cruz",
      "Tarija",
    ],
  },
  {
    label: "Bosnia and Herzegovina",
    value: "Bosnia and Herzegovina",
    country: "Bosnia and Herzegovina",
    states: [
      "Brčko District",
      "Federation of Bosnia and Herzegovina",
      "Republika Srpska",
    ],
  },
  {
    label: "Botswana",
    value: "Botswana",
    country: "Botswana",
    states: [
      "Central District",
      "Ghanzi District",
      "Kgalagadi District",
      "Kgatleng District",
      "Kweneng District",
      "North-East District",
      "North-West District",
      "South-East District",
      "Southern District",
    ],
  },
  {
    label: "Brazil",
    value: "Brazil",
    country: "Brazil",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Espírito Santo",
      "Federal District",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  {
    label: "Brunei",
    value: "Br Photographsunei",
    country: "Brunei",
    states: ["Belait", "Brunei-Muara", "Temburong", "Tutong"],
  },
  {
    label: "Bulgaria",
    value: "Bulgaria",
    country: "Bulgaria",
    states: [
      "Blagoevgrad Province",
      "Burgas Province",
      "Dobrich Province",
      "Gabrovo Province",
      "Haskovo Province",
      "Kardzhali Province",
      "Kyustendil Province",
      "Lovech Province",
      "Montana Province",
      "Pazardzhik Province",
      "Pernik Province",
      "Pleven Province",
      "Plovdiv Province",
      "Razgrad Province",
      "Ruse Province",
      "Shumen Province",
      "Silistra Province",
      "Sliven Province",
      "Smolyan Province",
      "Sofia City Province",
      "Sofia Province",
      "Stara Zagora Province",
      "Targovishte Province",
      "Varna Province",
      "Veliko Tarnovo Province",
      "Vidin Province",
      "Vratsa Province",
      "Yambol Province",
    ],
  },
  {
    label: "Burkina Faso",
    value: "Burkina Faso",
    country: "Burkina Faso",
    states: [
      "Balé",
      "Bam",
      "Banwa",
      "Bazèga",
      "Boucle du Mouhoun",
      "Bougouriba",
      "Boulgou",
      "Boulkiemdé",
      "Comoé",
      "Ganzourgou",
      "Gnagna",
      "Gourma",
      "Houet",
      "Ioba",
      "Kadiogo",
      "Kénédougou",
      "Komondjari",
      "Kompienga",
      "Kossi",
      "Koulpélogo",
      "Kouritenga",
      "Kourwéogo",
      "Léraba",
      "Loroum",
      "Mouhoun",
      "Nahouri",
      "Namentenga",
      "Nayala",
      "Noumbiel",
      "Oubritenga",
      "Oudalan",
      "Passoré",
      "Poni",
      "Sanguié",
      "Sanmatenga",
      "Séno",
      "Sissili",
      "Soum",
      "Sourou",
      "Tapoa",
      "Tuy",
      "Yagha",
      "Yatenga",
      "Ziro",
      "Zondoma",
      "Zoundwéogo",
    ],
  },
  {
    label: "Burundi",
    value: "Burundi",
    country: "Burundi",
    states: [
      "Bubanza",
      "Bujumbura Mairie",
      "Bujumbura Rural",
      "Bururi",
      "Cankuzo",
      "Cibitoke",
      "Gitega",
      "Karuzi",
      "Kayanza",
      "Kirundo",
      "Makamba",
      "Muramvya",
      "Muyinga",
      "Mwaro",
      "Ngozi",
      "Rumonge",
      "Rutana",
      "Ruyigi",
    ],
  },
  {
    label: "Cambodia",
    value: "Cambodia",
    country: "Cambodia",
    states: [
      "Banteay Meanchey",
      "Battambang",
      "Kampong Cham",
      "Kampong Chhnang",
      "Kampong Speu",
      "Kampong Thom",
      "Kampot",
      "Kandal",
      "Koh Kong",
      "Kratié",
      "Mondulkiri",
      "Oddar Meanchey",
      "Pailin",
      "Phnom Penh",
      "Preah Sihanouk",
      "Preah Vihear",
      "Pursat",
      "Ratanakiri",
      "Siem Reap",
      "Sihanoukville",
      "Stung Treng",
      "Svay Rieng",
      "Takéo",
      "Tbong Khmum",
    ],
  },
  {
    label: "Cameroon",
    value: "Cameroon",
    country: "Cameroon",
    states: [
      "Adamaoua",
      "Centre",
      "East",
      "Far North",
      "Littoral",
      "North",
      "Northwest",
      "South",
      "Southwest",
      "West",
    ],
  },
  {
    label: "Canada",
    value: "Canada",
    country: "Canada",
    states: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
    ],
  },
  {
    label: "Cape Verde",
    value: "Cape Verde",
    country: "Cape Verde",
    states: [
      "Boa Vista",
      "Brava",
      "Maio",
      "Mosteiros",
      "Paul",
      "Porto Novo",
      "Praia",
      "Ribeira Brava",
      "Ribeira Grande",
      "Ribeira Grande de Santiago",
      "Sal",
      "Santa Catarina",
      "Santa Catarina do Fogo",
      "Santa Cruz",
      "São Domingos",
      "São Filipe",
      "São Lourenço dos Órgãos",
      "São Miguel",
      "São Salvador do Mundo",
      "São Vicente",
      "Tarrafal",
      "Tarrafal de São Nicolau",
    ],
  },
  {
    label: "Central African Republic",
    value: "Central African Republic",
    country: "Central African Republic",
    states: [
      "Bamingui-Bangoran",
      "Bangui",
      "Basse-Kotto",
      "Haute-Kotto",
      "Haut-Mbomou",
      "Kémo",
      "Lobaye",
      "Mambéré-Kadéï",
      "Mbomou",
      "Nana-Grébizi",
      "Nana-Mambéré",
      "Ombella-M'Poko",
      "Ouaka",
      "Ouham",
      "Ouham-Pendé",
      "Sangha-Mbaéré",
      "Vakaga",
    ],
  },
  {
    label: "Chad",
    value: "Chad",
    country: "Chad",
    states: [
      "Bahr el Gazel",
      "Batha",
      "Borkou",
      "Chari-Baguirmi",
      "Ennedi",
      "Guéra",
      "Hadjer-Lamis",
      "Kanem",
      "Lac",
      "Logone Occidental",
      "Logone Oriental",
      "Mandoul",
      "Mayo-Kebbi Est",
      "Mayo-Kebbi Ouest",
      "Moyen-Chari",
      "N'Djamena",
      "Ouaddaï",
      "Salamat",
      "Sila",
      "Tandjilé",
      "Tibesti",
      "Wadi Fira",
    ],
  },
  {
    label: "Chile",
    value: "Chile",
    country: "Chile",
    states: [
      "Aisén",
      "Antofagasta",
      "Araucanía",
      "Arica y Parinacota",
      "Atacama",
      "Biobío",
      "Coquimbo",
      "Los Lagos",
      "Los Ríos",
      "Magallanes",
      "Maule",
      "Ñuble",
      "O'Higgins",
      "Santiago Metropolitan Region",
      "Tarapacá",
      "Valparaíso",
    ],
  },
  {
    label: "China",
    value: "China",
    country: "China",
    states: [
      "Anhui",
      "Beijing",
      "Chongqing",
      "Fujian",
      "Gansu",
      "Guangdong",
      "Guangxi",
      "Guizhou",
      "Hainan",
      "Hebei",
      "Heilongjiang",
      "Henan",
      "Hong Kong",
      "Hubei",
      "Hunan",
      "Inner Mongolia",
      "Jiangsu",
      "Jiangxi",
      "Jilin",
      "Liaoning",
      "Macau",
      "Ningxia",
      "Qinghai",
      "Shaanxi",
      "Shandong",
      "Shanghai",
      "Shanxi",
      "Sichuan",
      "Tianjin",
      "Tibet",
      "Xinjiang",
      "Yunnan",
      "Zhejiang",
    ],
  },
  {
    label: "Colombia",
    value: "Colombia",
    country: "Colombia",
    states: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bogotá",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés and Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ],
  },
  {
    label: "Comoros",
    value: "Comoros",
    country: "Comoros",
    states: ["Anjouan", "Grande Comore", "Mohéli"],
  },
  {
    label: "Congo (Brazzaville)",
    value: "Congo (Brazzaville)",
    country: "Congo (Brazzaville)",
    states: [
      "Bouenza",
      "Brazzaville",
      "Cuvette",
      "Cuvette-Ouest",
      "Kouilou",
      "Lékoumou",
      "Likouala",
      "Niari",
      "Plateaux",
      "Pointe-Noire",
      "Pool",
      "Sangha",
    ],
  },
  {
    label: "Congo (Kinshasa)",
    value: "Congo (Kinshasa)",
    country: "Congo (Kinshasa)",
    states: [
      "Bas-Uele",
      "Équateur",
      "Haut-Katanga",
      "Haut-Lomami",
      "Haut-Uele",
      "Ituri",
      "Kasaï",
      "Kasaï-Central",
      "Kasaï-Oriental",
      "Kinshasa",
      "Kwango",
      "Kwilu",
      "Lomami",
      "Lualaba",
      "Mai-Ndombe",
      "Maniema",
      "Mongala",
      "Nord-Ubangi",
      "Nord-Kivu",
      "Sankuru",
      "Sud-Ubangi",
      "Sud-Kivu",
      "Tanganyika",
      "Tshopo",
      "Tshuapa",
    ],
  },
  {
    label: "Costa Rica",
    value: "Costa Rica",
    country: "Costa Rica",
    states: [
      "Alajuela",
      "Cartago",
      "Guanacaste",
      "Heredia",
      "Limón",
      "Puntarenas",
      "San José",
    ],
  },
  {
    label: "Croatia",
    value: "Croatia",
    country: "Croatia",
    states: [
      "Bjelovar-Bilogora County",
      "Brod-Posavina County",
      "Dubrovnik-Neretva County",
      "Istria County",
      "Koprivnica-Križevci County",
      "Krapina-Zagorje County",
      "Lika-Senj County",
      "Međimurje County",
      "Osijek-Baranja County",
      "Požega-Slavonia County",
      "Primorje-Gorski Kotar County",
      "Šibenik-Knin County",
      "Sisak-Moslavina County",
      "Split-Dalmatia County",
      "Varaždin County",
      "Virovitica-Podravina County",
      "Vukovar-Syrmia County",
      "Zadar County",
      "Zagreb",
      "Zagreb County",
    ],
  },
  {
    label: "Cuba",
    value: "Cuba",
    country: "Cuba",
    states: [
      "Artemisa",
      "Camagüey",
      "Ciego de Ávila",
      "Cienfuegos",
      "Granma",
      "Guantánamo",
      "Havana",
      "Holguín",
      "Isla de la Juventud",
      "Las Tunas",
      "Matanzas",
      "Mayabeque",
      "Pinar del Río",
      "Sancti Spíritus",
      "Santiago de Cuba",
      "Villa Clara",
    ],
  },
  {
    label: "Cyprus",
    value: "Cyprus",
    country: "Cyprus",
    states: [
      "Famagusta District",
      "Kyrenia District",
      "Larnaca District",
      "Limassol District",
      "Nicosia District",
      "Paphos District",
    ],
  },
  {
    label: "Czech Republic",
    value: "Czech Republic",
    country: "Czech Republic",
    states: [
      "Central Bohemian Region",
      "Hradec Králové Region",
      "Karlovy Vary Region",
      "Liberec Region",
      "Moravian-Silesian Region",
      "Olomouc Region",
      "Pardubice Region",
      "Plzeň Region",
      "Prague",
      "South Bohemian Region",
      "South Moravian Region",
      "Ústí nad Labem Region",
      "Vysočina Region",
      "Zlín Region",
    ],
  },
  {
    label: "Denmark",
    value: "Denmark",
    country: "Denmark",
    states: [
      "Capital Region of Denmark",
      "Central Denmark Region",
      "North Denmark Region",
      "Region of Southern Denmark",
      "Region Zealand",
    ],
  },
  {
    label: "Djibouti",
    value: "Djibouti",
    country: "Djibouti",
    states: ["Ali Sabieh", "Arta", "Dikhil", "Djibouti", "Obock", "Tadjourah"],
  },
  {
    label: "Dominica",
    value: "Dominica",
    country: "Dominica",
    states: [
      "Saint Andrew Parish",
      "Saint David Parish",
      "Saint George Parish",
      "Saint John Parish",
      "Saint Joseph Parish",
      "Saint Luke Parish",
      "Saint Mark Parish",
      "Saint Patrick Parish",
      "Saint Paul Parish",
      "Saint Peter Parish",
    ],
  },
  {
    label: "Dominican Republic",
    value: "Dominican Republic",
    country: "Dominican Republic",
    states: [
      "Azua",
      "Baoruco",
      "Barahona",
      "Dajabón",
      "Distrito Nacional",
      "Duarte",
      "El Seibo",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "María Trinidad Sánchez",
      "Monseñor Nouel",
      "Monte Cristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samaná",
      "San Cristóbal",
      "San José de Ocoa",
      "San Juan",
      "San Pedro de Macorís",
      "Sánchez Ramírez",
      "Santiago",
      "Santiago Rodríguez",
      "Santo Domingo",
      "Valverde",
    ],
  },
  {
    label: "Ecuador",
    value: "Ecuador",
    country: "Ecuador",
    states: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
      "Zamora Chinchipe",
    ],
  },
  {
    label: "Egypt",
    value: "Egypt",
    country: "Egypt",
    states: [
      "Alexandria",
      "Aswan",
      "Asyut",
      "Beheira",
      "Beni Suef",
      "Cairo",
      "Dakahlia",
      "Damietta",
      "Faiyum",
      "Gharbia",
      "Giza",
      "Ismailia",
      "Kafr el-Sheikh",
      "Luxor",
      "Matruh",
      "Minya",
      "Monufia",
      "New Valley",
      "North Sinai",
      "Port Said",
      "Qalyubia",
      "Qena",
      "Red Sea",
      "Sharqia",
      "Sohag",
      "South Sinai",
      "Suez",
    ],
  },
  {
    label: "El Salvador",
    value: "El Salvador",
    country: "El Salvador",
    states: [
      "Ahuachapán",
      "Cabañas",
      "Chalatenango",
      "Cuscatlán",
      "La Libertad",
      "La Paz",
      "La Unión",
      "Morazán",
      "San Miguel",
      "San Salvador",
      "San Vicente",
      "Santa Ana",
      "Sonsonate",
      "Usulután",
    ],
  },
  {
    label: "Equatorial Guinea",
    value: "Equatorial Guinea",
    country: "Equatorial Guinea",
    states: [
      "Annobón",
      "Bioko Norte",
      "Bioko Sur",
      "Centro Sur",
      "Kié-Ntem",
      "Litoral",
      "Wele-Nzas",
    ],
  },
  {
    label: "Eritrea",
    value: "Eritrea",
    country: "Eritrea",
    states: [
      "Anseba",
      "Debub",
      "Debubawi Keyih Bahri",
      "Gash-Barka",
      "Maekel",
      "Semenawi Keyih Bahri",
    ],
  },
  {
    label: "Estonia",
    value: "Estonia",
    country: "Estonia",
    states: [
      "Harju",
      "Hiiu",
      "Ida-Viru",
      "Järva",
      "Jõgeva",
      "Lääne",
      "Lääne-Viru",
      "Põlva",
      "Pärnu",
      "Rapla",
      "Saare",
      "Tartu",
      "Valga",
      "Viljandi",
      "Võru",
    ],
  },
  {
    label: "Eswatini",
    value: "Eswatini",
    country: "Eswatini",
    states: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
  },
  {
    label: "Ethiopia",
    value: "Ethiopia",
    country: "Ethiopia",
    states: [
      "Addis Ababa",
      "Afar",
      "Amhara",
      "Benishangul-Gumuz",
      "Dire Dawa",
      "Gambela",
      "Harari",
      "Oromia",
      "Sidama",
      "Somali",
      "Southern Nations, Nationalities, and Peoples'",
      "Tigray",
    ],
  },
  {
    label: "Fiji",
    value: "Fiji",
    country: "Fiji",
    states: [
      "Ba",
      "Bua",
      "Cakaudrove",
      "Kadavu",
      "Lau",
      "Lomaiviti",
      "Macuata",
      "Nadroga-Navosa",
      "Naitasiri",
      "Namosi",
      "Ra",
      "Rewa",
      "Rotuma",
      "Serua",
      "Tailevu",
    ],
  },
  {
    label: "Finland",
    value: "Finland",
    country: "Finland",
    states: [
      "Åland",
      "Central Finland",
      "Central Ostrobothnia",
      "Eastern Finland",
      "Kainuu",
      "Kanta-Häme",
      "Kymenlaakso",
      "Lapland",
      "North Karelia",
      "North Ostrobothnia",
      "Northern Savonia",
      "Ostrobothnia",
      "Päijänne Tavastia",
      "Pirkanmaa",
      "Satakunta",
      "South Karelia",
      "South Ostrobothnia",
      "Southern Savonia",
      "Uusimaa",
      "Varsinais-Suomi",
    ],
  },
  {
    label: "France",
    value: "France",
    country: "France",
    states: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  {
    label: "Gabon",
    value: "Gabon",
    country: "Gabon",
    states: [
      "Estuaire",
      "Haut-Ogooué",
      "Moyen-Ogooué",
      "Ngounié",
      "Nyanga",
      "Ogooué-Ivindo",
      "Ogooué-Lolo",
      "Ogooué-Maritime",
      "Woleu-Ntem",
    ],
  },
  {
    label: "Gambia",
    value: "Gambia",
    country: "Gambia",
    states: [
      "Banjul",
      "Central River",
      "Lower River",
      "North Bank",
      "Upper River",
      "West Coast",
    ],
  },
  {
    label: "Georgia",
    value: "Georgia",
    country: "Georgia",
    states: [
      "Abkhazia",
      "Adjara",
      "Guria",
      "Imereti",
      "Kakheti",
      "Kvemo Kartli",
      "Mtskheta-Mtianeti",
      "Racha-Lechkhumi and Kvemo Svaneti",
      "Samegrelo-Zemo Svaneti",
      "Samtskhe-Javakheti",
      "Shida Kartli",
      "Tbilisi",
    ],
  },
  {
    label: "Germany",
    value: "Germany",
    country: "Germany",
    states: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Western Pomerania",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  {
    label: "Ghana",
    value: "Ghana",
    country: "Ghana",
    states: [
      "Ahafo",
      "Ashanti",
      "Bono",
      "Bono East",
      "Central",
      "Eastern",
      "Greater Accra",
      "Northern",
      "Oti",
      "Savannah",
      "Upper East",
      "Upper West",
      "Volta",
      "Western",
      "Western North",
    ],
  },
  {
    label: "Greece",
    value: "Greece",
    country: "Greece",
    states: [
      "Aegean Islands",
      "Attica",
      "Central Greece",
      "Central Macedonia",
      "Crete",
      "Eastern Macedonia and Thrace",
      "Epirus",
      "Ionian Islands",
      "Peloponnese",
      "Thessaly",
      "Western Greece",
      "Western Macedonia",
    ],
  },
  {
    label: "Grenada",
    value: "Grenada",
    country: "Grenada",
    states: [
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Mark",
      "Saint Patrick",
    ],
  },
  {
    label: "Guatemala",
    value: "Guatemala",
    country: "Guatemala",
    states: [
      "Alta Verapaz",
      "Baja Verapaz",
      "Chimaltenango",
      "Chiquimula",
      "El Progreso",
      "Escuintla",
      "Guatemala",
      "Huehuetenango",
      "Izabal",
      "Jalapa",
      "Jutiapa",
      "Petén",
      "Quetzaltenango",
      "Quiché",
      "Retalhuleu",
      "Sacatepéquez",
      "San Marcos",
      "Santa Rosa",
      "Sololá",
      "Suchitepéquez",
      "Totonicapán",
      "Zacapa",
    ],
  },
  {
    label: "Guinea",
    value: "Guinea",
    country: "Guinea",
    states: [
      "Beyla",
      "Boffa",
      "Boké",
      "Conakry",
      "Coyah",
      "Dabola",
      "Dalaba",
      "Dinguiraye",
      "Dubréka",
      "Faranah",
      "Forécariah",
      "Fria",
      "Gaoual",
      "Kankan",
      "Kérouané",
      "Kindia",
      "Kissidougou",
      "Koubia",
      "Koundara",
      "Kouroussa",
      "Labé",
      "Lelouma",
      "Lola",
      "Macenta",
      "Mali",
      "Mamou",
      "Mandiana",
      "Nzérékoré",
      "Pita",
      "Siguiri",
      "Télimélé",
      "Tougué",
      "Yomou",
    ],
  },
  {
    label: "Guinea-Bissau",
    value: "Guinea-Bissau",
    country: "Guinea-Bissau",
    states: [
      "Bafatá",
      "Biombo",
      "Bissau",
      "Bolama",
      "Cacheu",
      "Gabú",
      "Oio",
      "Quinara",
      "Tombali",
    ],
  },
  {
    label: "Guyana",
    value: "Guyana",
    country: "Guyana",
    states: [
      "Barima-Waini",
      "Cuyuni-Mazaruni",
      "Demerara-Mahaica",
      "East Berbice-Corentyne",
      "Essequibo Islands-West Demerara",
      "Mahaica-Berbice",
      "Pomeroon-Supenaam",
      "Potaro-Siparuni",
      "Upper Demerara-Berbice",
      "Upper Takutu-Upper Essequibo",
    ],
  },
  {
    label: "Haiti",
    value: "Haiti",
    country: "Haiti",
    states: [
      "Artibonite",
      "Centre",
      "Grand'Anse",
      "Nippes",
      "Nord",
      "Nord-Est",
      "Nord-Ouest",
      "Ouest",
      "Sud",
      "Sud-Est",
    ],
  },
  {
    label: "Honduras",
    value: "Honduras",
    country: "Honduras",
    states: [
      "Atlántida",
      "Choluteca",
      "Colón",
      "Comayagua",
      "Copán",
      "Cortés",
      "El Paraíso",
      "Francisco Morazán",
      "Gracias a Dios",
      "Intibucá",
      "Islas de la Bahía",
      "La Paz",
      "Lempira",
      "Ocotepeque",
      "Olancho",
      "Santa Bárbara",
      "Valle",
      "Yoro",
    ],
  },
  {
    label: "Hungary",
    value: "Hungary",
    country: "Hungary",
    states: [
      "Bács-Kiskun",
      "Baranya",
      "Békés",
      "Békéscsaba",
      "Borsod-Abaúj-Zemplén",
      "Budapest",
      "Csongrád-Csanád",
      "Debrecen",
      "Dunaújváros",
      "Eger",
      "Fejér",
      "Győr-Moson-Sopron",
      "Hajdú-Bihar",
      "Heves",
      "Hódmezővásárhely",
      "Jász-Nagykun-Szolnok",
      "Kaposvár",
      "Kecskemét",
      "Komárom-Esztergom",
      "Miskolc",
      "Nagykanizsa",
      "Nógrád",
      "Nyíregyháza",
      "Pécs",
      "Pest",
      "Salgótarján",
      "Somogy",
      "Sopron",
      "Szabolcs-Szatmár-Bereg",
      "Szeged",
      "Székesfehérvár",
      "Szolnok",
      "Szombathely",
      "Tatabánya",
      "Tolna",
      "Vas",
      "Veszprém",
      "Zala",
    ],
  },
  {
    label: "Iceland",
    value: "Iceland",
    country: "Iceland",
    states: [
      "Austurland",
      "Höfuðborgarsvæðið",
      "Norðurland eystra",
      "Norðurland vestra",
      "Suðurland",
      "Suðurnes",
      "Vestfirðir",
      "Vesturland",
    ],
  },
  {
    label: "India",
    value: "India",
    country: "India",
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Lakshadweep",
      "Delhi",
      "Puducherry",
    ],
  },
  {
    label: "Indonesia",
    value: "Indonesia",
    country: "Indonesia",
    states: [
      "Aceh",
      "Bali",
      "Bangka Belitung",
      "Banten",
      "Bengkulu",
      "Central Java",
      "Central Kalimantan",
      "Central Sulawesi",
      "East Java",
      "East Kalimantan",
      "East Nusa Tenggara",
      "Gorontalo",
      "Jakarta",
      "Jambi",
      "Lampung",
      "Maluku",
      "North Kalimantan",
      "North Maluku",
      "North Sulawesi",
      "North Sumatra",
      "Papua",
      "Riau",
      "Riau Islands",
      "Southeast Sulawesi",
      "South Kalimantan",
      "South Sulawesi",
      "South Sumatra",
      "West Java",
      "West Kalimantan",
      "West Nusa Tenggara",
      "West Papua",
      "West Sulawesi",
      "West Sumatra",
      "Yogyakarta",
    ],
  },
  {
    label: "Iran",
    value: "Iran",
    country: "Iran",
    states: [
      "Alborz",
      "Ardabil",
      "Bushehr",
      "Chaharmahal and Bakhtiari",
      "East Azerbaijan",
      "Esfahan",
      "Fars",
      "Gilan",
      "Golestan",
      "Hamadan",
      "Hormozgan",
      "Ilam",
      "Kerman",
      "Kermanshah",
      "Khuzestan",
      "Kohgiluyeh and Boyer-Ahmad",
      "Kurdistan",
      "Lorestan",
      "Markazi",
      "Mazandaran",
      "North Khorasan",
      "Qazvin",
      "Qom",
      "Razavi Khorasan",
      "Semnan",
      "Sistan and Baluchestan",
      "South Khorasan",
      "Tehran",
      "West Azerbaijan",
      "Yazd",
      "Zanjan",
    ],
  },
  {
    label: "Iraq",
    value: "Iraq",
    country: "Iraq",
    states: [
      "Al Anbar",
      "Al Muthanna",
      "Al Qadisiyyah",
      "Babylon",
      "Baghdad",
      "Basra",
      "Dhi Qar",
      "Diyala",
      "Duhok",
      "Erbil",
      "Karbala",
      "Kirkuk",
      "Maysan",
      "Najaf",
      "Nineveh",
      "Saladin",
      "Sulaymaniyah",
      "Wasit",
    ],
  },
  {
    label: "Ireland",
    value: "Ireland",
    country: "Ireland",
    states: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
  },
  {
    label: "Israel",
    value: "Israel",
    country: "Israel",
    states: [
      "Central District",
      "Haifa District",
      "Jerusalem District",
      "Northern District",
      "Southern District",
      "Tel Aviv District",
    ],
  },
  {
    label: "Italy",
    value: "Italy",
    country: "Italy",
    states: [
      "Abruzzo",
      "Aosta Valley",
      "Apulia",
      "Basilicata",
      "Calabria",
      "Campania",
      "Emilia-Romagna",
      "Friuli Venezia Giulia",
      "Lazio",
      "Liguria",
      "Lombardy",
      "Marche",
      "Molise",
      "Piedmont",
      "Sardinia",
      "Sicily",
      "Trentino-South Tyrol",
      "Tuscany",
      "Umbria",
      "Veneto",
    ],
  },
  {
    label: "Jamaica",
    value: "Jamaica",
    country: "Jamaica",
    states: [
      "Clarendon",
      "Hanover",
      "Kingston",
      "Manchester",
      "Portland",
      "Saint Andrew",
      "Saint Ann",
      "Saint Catherine",
      "Saint Elizabeth",
      "Saint James",
      "Saint Mary",
      "Saint Thomas",
      "Trelawny",
      "Westmoreland",
    ],
  },
  {
    label: "Japan",
    value: "Japan",
    country: "Japan",
    states: [
      "Aichi",
      "Akita",
      "Aomori",
      "Chiba",
      "Ehime",
      "Fukui",
      "Fukuoka",
      "Fukushima",
      "Gifu",
      "Gunma",
      "Hiroshima",
      "Hokkaido",
      "Hyogo",
      "Ibaraki",
      "Ishikawa",
      "Iwate",
      "Kagawa",
      "Kagoshima",
      "Kanagawa",
      "Kochi",
      "Kumamoto",
      "Kyoto",
      "Mie",
      "Miyagi",
      "Miyazaki",
      "Nagano",
      "Nagasaki",
      "Nara",
      "Niigata",
      "Oita",
      "Okayama",
      "Okinawa",
      "Osaka",
      "Saga",
      "Saitama",
      "Shiga",
      "Shimane",
      "Shizuoka",
      "Tochigi",
      "Tokushima",
      "Tokyo",
      "Tottori",
      "Toyama",
      "Wakayama",
      "Yamagata",
      "Yamaguchi",
      "Yamanashi",
    ],
  },
  {
    label: "Jordan",
    value: "Jordan",
    country: "Jordan",
    states: [
      "Ajloun",
      "Amman",
      "Aqaba",
      "Balqa",
      "Irbid",
      "Jerash",
      "Karak",
      "Ma'an",
      "Madaba",
      "Mafraq",
      "Tafilah",
      "Zarqa",
    ],
  },
  {
    label: "Kazakhstan",
    value: "Kazakhstan",
    country: "Kazakhstan",
    states: [
      "Akmola",
      "Aktobe",
      "Almaty",
      "Atyrau",
      "Baikonur",
      "East Kazakhstan",
      "Jambyl",
      "Karaganda",
      "Kostanay",
      "Kyzylorda",
      "Mangystau",
      "North Kazakhstan",
      "Nur-Sultan",
      "Pavlodar",
      "Shymkent",
      "Turkistan",
      "West Kazakhstan",
    ],
  },
  {
    label: "Kenya",
    value: "Kenya",
    country: "Kenya",
    states: [
      "Baringo",
      "Bomet",
      "Bungoma",
      "Busia",
      "Elgeyo-Marakwet",
      "Embu",
      "Garissa",
      "Homa Bay",
      "Isiolo",
      "Kajiado",
      "Kakamega",
      "Kericho",
      "Kiambu",
      "Kilifi",
      "Kirinyaga",
      "Kisii",
      "Kisumu",
      "Kitui",
      "Kwale",
      "Laikipia",
      "Lamu",
      "Machakos",
      "Makueni",
      "Mandera",
      "Marsabit",
      "Meru",
      "Migori",
      "Mombasa",
      "Murang'a",
      "Nairobi",
      "Nakuru",
      "Nandi",
      "Narok",
      "Nyamira",
      "Nyandarua",
      "Nyeri",
      "Samburu",
      "Siaya",
      "Taita-Taveta",
      "Tana River",
      "Tharaka-Nithi",
      "Trans Nzoia",
      "Turkana",
      "Uasin Gishu",
      "Vihiga",
      "Wajir",
      "West Pokot",
    ],
  },
  {
    label: "Kiribati",
    value: "Kiribati",
    country: "Kiribati",
    states: ["Gilbert Islands", "Line Islands", "Phoenix Islands"],
  },
  {
    label: "Kuwait",
    value: "Kuwait",
    country: "Kuwait",
    states: [
      "Al Ahmadi",
      "Al Farwaniyah",
      "Al Asimah",
      "Al Jahra",
      "Hawalli",
      "Mubarak Al-Kabeer",
    ],
  },
  {
    label: "Kyrgyzstan",
    value: "Kyrgyzstan",
    country: "Kyrgyzstan",
    states: [
      "Batken",
      "Chuy",
      "Issyk-Kul",
      "Jalal-Abad",
      "Naryn",
      "Osh",
      "Talas",
    ],
  },
  {
    label: "Laos",
    value: "Laos",
    country: "Laos",
    states: [
      "Attapeu",
      "Bokeo",
      "Bolikhamsai",
      "Champasak",
      "Houaphanh",
      "Khammouane",
      "Luang Namtha",
      "Luang Prabang",
      "Oudomxay",
      "Phongsaly",
      "Salavan",
      "Savannakhet",
      "Sekong",
      "Vientiane",
      "Vientiane Prefecture",
      "Xaignabouli",
      "Xaisomboun",
      "Xiangkhouang",
    ],
  },
  {
    label: "Latvia",
    value: "Latvia",
    country: "Latvia",
    states: [
      "Aizkraukle",
      "Aluksne",
      "Balvi",
      "Bauska",
      "Cesis",
      "Daugavpils",
      "Dobele",
      "Gulbene",
      "Jekabpils",
      "Jelgava",
      "Jurmala",
      "Kraslava",
      "Kuldiga",
      "Liepaja",
      "Limbazi",
      "Ludza",
      "Madona",
      "Ogre",
      "Preili",
      "Rezekne",
      "Riga",
      "Saldus",
      "Talsi",
      "Tukums",
      "Valka",
      "Valmiera",
      "Ventspils",
    ],
  },
  {
    label: "Lebanon",
    value: "Lebanon",
    country: "Lebanon",
    states: [
      "Akkar",
      "Baalbek-Hermel",
      "Beirut",
      "Bekaa",
      "Keserwan-Jbeil",
      "Mount Lebanon",
      "North Lebanon",
      "South Lebanon",
    ],
  },
  {
    label: "Lesotho",
    value: "Lesotho",
    country: "Lesotho",
    states: [
      "Berea",
      "Butha-Buthe",
      "Leribe",
      "Mafeteng",
      "Maseru",
      "Mohale's Hoek",
      "Mokhotlong",
      "Qacha's Nek",
      "Quthing",
      "Thaba-Tseka",
    ],
  },
  {
    label: "Liberia",
    value: "Liberia",
    country: "Liberia",
    states: [
      "Bomi",
      "Bong",
      "Gbarpolu",
      "Grand Bassa",
      "Grand Cape Mount",
      "Grand Gedeh",
      "Grand Kru",
      "Lofa",
      "Margibi",
      "Maryland",
      "Montserrado",
      "Nimba",
      "Rivercess",
      "River Gee",
      "Sinoe",
    ],
  },
  {
    label: "Libya",
    value: "Libya",
    country: "Libya",
    states: [
      "Al Butnan",
      "Al Jabal al Akhdar",
      "Al Jabal al Gharbi",
      "Al Jafara",
      "Al Kufra",
      "Al Marj",
      "Al Marqab",
      "Al Wahat",
      "An Nuqat al Khams",
      "Az Zawiyah",
      "Benghazi",
      "Darnah",
      "Ghat",
      "Ghadamis",
      "Gharyan",
      "Misratah",
      "Murzuq",
      "Nalut",
      "Sabha",
      "Surt",
      "Tarhunah",
      "Tripoli",
      "Ubari",
      "Wadi al Hayat",
      "Wadi ash Shati",
      "Zliten",
    ],
  },
  {
    label: "Liechtenstein",
    value: "Liechtenstein",
    country: "Liechtenstein",
    states: [
      "Balzers",
      "Eschen",
      "Gamprin",
      "Mauren",
      "Planken",
      "Ruggell",
      "Schaan",
      "Schellenberg",
      "Triesen",
      "Triesenberg",
      "Vaduz",
    ],
  },
  {
    label: "Lithuania",
    value: "Lithuania",
    country: "Lithuania",
    states: [
      "Alytus",
      "Kaunas",
      "Klaipeda",
      "Marijampole",
      "Panevezys",
      "Siauliai",
      "Taurage",
      "Telsiai",
      "Utena",
      "Vilnius",
    ],
  },
  {
    label: "Luxembourg",
    value: "Luxembourg",
    country: "Luxembourg",
    states: [
      "Capellen",
      "Clervaux",
      "Diekirch",
      "Echternach",
      "Esch-sur-Alzette",
      "Grevenmacher",
      "Luxembourg",
      "Mersch",
      "Redange",
      "Remich",
      "Vianden",
      "Wiltz",
    ],
  },
  {
    label: "Madagascar",
    value: "Madagascar",
    country: "Madagascar",
    states: [
      "Antananarivo",
      "Antsiranana",
      "Fianarantsoa",
      "Mahajanga",
      "Toamasina",
      "Toliara",
    ],
  },
  {
    label: "Malawi",
    value: "Malawi",
    country: "Malawi",
    states: ["Central Region", "Northern Region", "Southern Region"],
  },
  {
    label: "Malaysia",
    value: "Malaysia",
    country: "Malaysia",
    states: [
      "Johor",
      "Kedah",
      "Kelantan",
      "Malacca",
      "Negeri Sembilan",
      "Pahang",
      "Penang",
      "Perak",
      "Perlis",
      "Sabah",
      "Sarawak",
      "Selangor",
      "Terengganu",
    ],
  },
  {
    label: "Maldives",
    value: "Maldives",
    country: "Maldives",
    states: [
      "Addu City",
      "Fuvahmulah City",
      "Malé City",
      "Upper North Province",
      "North Central Province",
      "Upper South Province",
      "South Central Province",
    ],
  },
  {
    label: "Mali",
    value: "Mali",
    country: "Mali",
    states: [
      "Bamako",
      "Gao",
      "Kayes",
      "Kidal",
      "Koulikoro",
      "Mopti",
      "Ségou",
      "Sikasso",
      "Tombouctou",
    ],
  },
  {
    label: "Malta",
    value: "Malta",
    country: "Malta",
    states: [
      "Attard",
      "Balzan",
      "Birgu",
      "Birkirkara",
      "Birzebbuga",
      "Cospicua",
      "Dingli",
      "Fgura",
      "Floriana",
      "Fontana",
      "Gudja",
      "Gzira",
      "Hamrun",
      "Iklin",
      "Isla",
      "Kalkara",
      "Kercem",
      "Kirkop",
      "Lija",
      "Luqa",
    ],
  },
  {
    label: "Mauritania",
    value: "Mauritania",
    country: "Mauritania",
    states: [
      "Adrar",
      "Assaba",
      "Brakna",
      "Dakhlet Nouadhibou",
      "Gorgol",
      "Guidimaka",
      "Hodh Ech Chargui",
      "Hodh El Gharbi",
      "Inchiri",
      "Nouakchott Nord",
      "Nouakchott Ouest",
      "Nouakchott Sud",
      "Tagant",
      "Tiris Zemmour",
      "Trarza",
    ],
  },
  {
    label: "Mauritius",
    value: "Mauritius",
    country: "Mauritius",
    states: [
      "Agalega Islands",
      "Beau Bassin-Rose Hill",
      "Cargados Carajos",
      "Curepipe",
      "Moka",
      "Pamplemousses",
      "Plaines Wilhems",
      "Port Louis",
      "Quatre Bornes",
      "Rodrigues Island",
      "Savanne",
      "Vacoas-Phoenix",
    ],
  },
  {
    label: "Mexico",
    value: "Mexico",
    country: "Mexico",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Mexico City",
      "Mexico State",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  {
    label: "Micronesia",
    value: "Micronesia",
    country: "Micronesia",
    states: ["Chuuk", "Kosrae", "Pohnpei", "Yap"],
  },
  {
    label: "Moldova",
    value: "Moldova",
    country: "Moldova",
    states: [
      "Anenii Noi",
      "Bălți",
      "Basarabeasca",
      "Bender",
      "Briceni",
      "Cahul",
      "Cantemir",
      "Călărași",
      "Cimișlia",
      "Criuleni",
      "Dondușeni",
      "Drochia",
      "Dubăsari",
      "Edineț",
      "Fălești",
      "Florești",
      "Glodeni",
      "Hîncești",
      "Ialoveni",
      "Leova",
      "Nisporeni",
      "Ocnița",
      "Orhei",
      "Rezina",
      "Rîșcani",
      "Șoldănești",
      "Soroca",
      "Strășeni",
      "Ștefan Vodă",
      "Taraclia",
      "Telenești",
      "Ungheni",
    ],
  },
  {
    label: "Monaco",
    value: "Monaco",
    country: "Monaco",
    states: ["La Condamine", "Monaco-Ville", "Monte Carlo", "Fontvieille"],
  },
  {
    label: "Mongolia",
    value: "Mongolia",
    country: "Mongolia",
    states: [
      "Arkhangai",
      "Bayan-Ölgii",
      "Bayankhongor",
      "Bulgan",
      "Darkhan-Uul",
      "Dornod",
      "Dornogovi",
      "Dundgovi",
      "Govi-Altai",
      "Govisümber",
      "Khentii",
      "Khovd",
      "Khövsgöl",
      "Ömnögovi",
      "Orkhon",
      "Selenge",
      "Sükhbaatar",
      "Töv",
      "Uvs",
      "Zavkhan",
    ],
  },
  {
    label: "Montenegro",
    value: "Montenegro",
    country: "Montenegro",
    states: [
      "Andrijevica",
      "Bar",
      "Berane",
      "Bijelo Polje",
      "Budva",
      "Cetinje",
      "Danilovgrad",
      "Gusinje",
      "Herceg Novi",
      "Kolašin",
      "Kotor",
      "Mojkovac",
      "Nikšić",
      "Petnjica",
      "Plav",
      "Pljevlja",
      "Plužine",
      "Podgorica",
      "Rožaje",
      "Šavnik",
      "Tivat",
      "Ulcinj",
      "Žabljak",
    ],
  },
  {
    label: "Morocco",
    value: "Morocco",
    country: "Morocco",
    states: [
      "Casablanca-Settat",
      "Drâa-Tafilalet",
      "Dakhla-Oued Ed-Dahab",
      "Fès-Meknès",
      "Guelmim-Oued Noun",
      "Laâyoune-Sakia El Hamra",
      "Marrakech-Safi",
      "Oriental",
      "Rabat-Salé-Kénitra",
      "Souss-Massa",
      "Tanger-Tétouan-Al Hoceïma",
      "Béni Mellal-Khénifra",
    ],
  },
  {
    label: "Mozambique",
    value: "Mozambique",
    country: "Mozambique",
    states: [
      "Cabo Delgado",
      "Gaza",
      "Inhambane",
      "Manica",
      "Maputo City",
      "Maputo Province",
      "Nampula",
      "Niassa",
      "Sofala",
      "Tete",
      "Zambezia",
    ],
  },
  {
    label: "Namibia",
    value: "Namibia",
    country: "Namibia",
    states: [
      "Erongo",
      "Hardap",
      "Karas",
      "Kavango East",
      "Kavango West",
      "Khomas",
      "Kunene",
      "Ohangwena",
      "Omaheke",
      "Omusati",
      "Oshana",
      "Oshikoto",
      "Otjozondjupa",
      "Zambezi",
    ],
  },
  {
    label: "Nauru",
    value: "Nauru",
    country: "Nauru",
    states: [
      "Aiwo",
      "Anabar",
      "Anetan",
      "Anibare",
      "Baiti",
      "Boe",
      "Buada",
      "Denigomodu",
      "Ewa",
      "Ijuw",
      "Meneng",
      "Nibok",
      "Uaboe",
      "Yaren",
    ],
  },
  {
    label: "Nepal",
    value: "Nepal",
    country: "Nepal",
    states: [
      "Bagmati Province",
      "Gandaki Province",
      "Karnali Province",
      "Lumbini Province",
      "Madhesh Province",
      "Province No. 1",
      "Sudurpashchim Province",
    ],
  },
  {
    label: "Netherlands",
    value: "Netherlands",
    country: "Netherlands",
    states: [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "North Brabant",
      "North Holland",
      "Overijssel",
      "South Holland",
      "Utrecht",
      "Zeeland",
    ],
  },
  {
    label: "New Zealand",
    value: "New Zealand",
    country: "New Zealand",
    states: [
      "Auckland",
      "Bay of Plenty",
      "Canterbury",
      "Gisborne",
      "Hawke's Bay",
      "Manawatu-Wanganui",
      "Marlborough",
      "Nelson",
      "Northland",
      "Otago",
      "Southland",
      "Taranaki",
      "Tasman",
      "Waikato",
      "Wellington",
      "West Coast",
    ],
  },
  {
    label: "Nicaragua",
    value: "Nicaragua",
    country: "Nicaragua",
    states: [
      "Boaco",
      "Carazo",
      "Chinandega",
      "Chontales",
      "Estelí",
      "Granada",
      "Jinotega",
      "León",
      "Madriz",
      "Managua",
      "Masaya",
      "Matagalpa",
      "Nueva Segovia",
      "Río San Juan",
      "Rivas",
      "South Caribbean Coast",
      "North Caribbean Coast",
    ],
  },
  {
    label: "Niger",
    value: "Niger",
    country: "Niger",
    states: [
      "Agadez",
      "Diffa",
      "Dosso",
      "Maradi",
      "Tahoua",
      "Tillabéri",
      "Zinder",
      "Niamey",
    ],
  },
  {
    label: "North Korea",
    value: "North Korea",
    country: "North Korea",
    states: [
      "Chagang",
      "North Hamgyong",
      "South Hamgyong",
      "North Hwanghae",
      "South Hwanghae",
      "Kangwon",
      "North Pyongan",
      "South Pyongan",
      "Ryanggang",
    ],
  },
  {
    label: "North Macedonia",
    value: "North Macedonia",
    country: "North Macedonia",
    states: [
      "Eastern",
      "Northeastern",
      "Pelagonia",
      "Polog",
      "Skopje",
      "Southeastern",
      "Southwestern",
      "Vardar",
    ],
  },
  {
    label: "Norway",
    value: "Norway",
    country: "Norway",
    states: [
      "Agder",
      "Innlandet",
      "Møre og Romsdal",
      "Nordland",
      "Oslo",
      "Rogaland",
      "Troms og Finnmark",
      "Trøndelag",
      "Vestfold og Telemark",
      "Vestland",
      "Viken",
    ],
  },
  {
    label: "Oman",
    value: "Oman",
    country: "Oman",
    states: [
      "Ad Dakhiliyah",
      "Ad Dhahirah",
      "Al Batinah North",
      "Al Batinah South",
      "Al Buraimi",
      "Al Wusta",
      "Dhofar",
      "Musandam",
      "Muscat",
      "Ash Sharqiyah North",
      "Ash Sharqiyah South",
    ],
  },
  {
    label: "Pakistan",
    value: "Pakistan",
    country: "Pakistan",
    states: [
      "Balochistan",
      "Khyber Pakhtunkhwa",
      "Punjab",
      "Sindh",
      "Gilgit-Baltistan",
      "Azad Jammu and Kashmir",
      "Islamabad Capital Territory",
    ],
  },
  {
    label: "Palau",
    value: "Palau",
    country: "Palau",
    states: [
      "Aimeliik",
      "Airai",
      "Angaur",
      "Hatohobei",
      "Kayangel",
      "Koror",
      "Melekeok",
      "Ngaraard",
      "Ngarchelong",
      "Ngardmau",
      "Ngatpang",
      "Ngchesar",
      "Ngeremlengui",
      "Ngiwal",
      "Peleliu",
      "Sonsorol",
    ],
  },
  {
    label: "Panama",
    value: "Panama",
    country: "Panama",
    states: [
      "Bocas del Toro",
      "Chiriquí",
      "Coclé",
      "Colón",
      "Darién",
      "Herrera",
      "Los Santos",
      "Panamá",
      "Veraguas",
      "Panamá Oeste",
      "Emberá",
      "Guna Yala",
      "Ngäbe-Buglé",
    ],
  },
  {
    label: "Papua New Guinea",
    value: "Papua New Guinea",
    country: "Papua New Guinea",
    states: [
      "Central",
      "Chimbu",
      "Eastern Highlands",
      "East New Britain",
      "East Sepik",
      "Enga",
      "Gulf",
      "Hela",
      "Jiwaka",
      "Madang",
      "Manus",
      "Milne Bay",
      "Morobe",
      "New Ireland",
      "Northern",
      "Southern Highlands",
      "Western",
      "Western Highlands",
      "West New Britain",
      "West Sepik",
      "National Capital District",
      "Bougainville",
    ],
  },
  {
    label: "Paraguay",
    value: "Paraguay",
    country: "Paraguay",
    states: [
      "Alto Paraguay",
      "Alto Paraná",
      "Amambay",
      "Boquerón",
      "Caaguazú",
      "Caazapá",
      "Canindeyú",
      "Central",
      "Concepción",
      "Cordillera",
      "Guairá",
      "Itapúa",
      "Misiones",
      "Ñeembucú",
      "Paraguarí",
      "Presidente Hayes",
      "San Pedro",
      "Asunción",
    ],
  },
  {
    label: "Peru",
    value: "Peru",
    country: "Peru",
    states: [
      "Amazonas",
      "Áncash",
      "Apurímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
  {
    label: "Philippines",
    value: "Philippines",
    country: "Philippines",
    states: [
      "Abra",
      "Agusan del Norte",
      "Agusan del Sur",
      "Aklan",
      "Albay",
      "Antique",
      "Apayao",
      "Aurora",
      "Basilan",
      "Bataan",
      "Batanes",
      "Batangas",
      "Benguet",
      "Biliran",
      "Bohol",
      "Bukidnon",
      "Bulacan",
      "Cagayan",
      "Camarines Norte",
      "Camarines Sur",
      "Camiguin",
      "Capiz",
      "Catanduanes",
      "Cavite",
      "Cebu",
      "Cotabato",
      "Davao de Oro",
      "Davao del Norte",
      "Davao del Sur",
      "Davao Occidental",
      "Davao Oriental",
      "Dinagat Islands",
      "Eastern Samar",
      "Guimaras",
      "Ifugao",
      "Ilocos Norte",
      "Ilocos Sur",
      "Iloilo",
      "Isabela",
      "Kalinga",
      "La Union",
      "Laguna",
      "Lanao del Norte",
      "Lanao del Sur",
      "Leyte",
      "Maguindanao del Norte",
      "Maguindanao del Sur",
      "Marinduque",
      "Masbate",
      "Misamis Occidental",
      "Misamis Oriental",
      "Mountain Province",
      "Negros Occidental",
      "Negros Oriental",
      "Northern Samar",
      "Nueva Ecija",
      "Nueva Vizcaya",
      "Occidental Mindoro",
      "Oriental Mindoro",
      "Palawan",
      "Pampanga",
      "Pangasinan",
      "Quezon",
      "Quirino",
      "Rizal",
      "Romblon",
      "Samar",
      "Sarangani",
      "Siquijor",
      "Sorsogon",
      "South Cotabato",
      "Southern Leyte",
      "Sultan Kudarat",
      "Sulu",
      "Surigao del Norte",
      "Surigao del Sur",
      "Tarlac",
      "Tawi-Tawi",
      "Zambales",
      "Zamboanga del Norte",
      "Zamboanga del Sur",
      "Zamboanga Sibugay",
      "Metro Manila",
    ],
  },
  {
    label: "Poland",
    value: "Poland",
    country: "Poland",
    states: [
      "Greater Poland",
      "Kuyavian-Pomeranian",
      "Lesser Poland",
      "Łódź",
      "Lower Silesian",
      "Lublin",
      "Lubusz",
      "Masovian",
      "Opole",
      "Podkarpackie",
      "Podlaskie",
      "Pomeranian",
      "Silesian",
      "Świętokrzyskie",
      "Warmian-Masurian",
      "West Pomeranian",
    ],
  },
  {
    label: "Portugal",
    value: "Portugal",
    country: "Portugal",
    states: [
      "Aveiro",
      "Beja",
      "Braga",
      "Bragança",
      "Castelo Branco",
      "Coimbra",
      "Évora",
      "Faro",
      "Guarda",
      "Leiria",
      "Lisbon",
      "Portalegre",
      "Porto",
      "Santarém",
      "Setúbal",
      "Viana do Castelo",
      "Vila Real",
      "Viseu",
      "Azores",
      "Madeira",
    ],
  },
  {
    label: "Qatar",
    value: "Qatar",
    country: "Qatar",
    states: [
      "Ad Dawhah",
      "Al Khawr wa adh Dhakhirah",
      "Al Wakrah",
      "Ar Rayyan",
      "Ash Shamal",
      "Az Za'ayin",
      "Umm Salal",
      "Al-Shahaniya",
    ],
  },
  {
    label: "Romania",
    value: "Romania",
    country: "Romania",
    states: [
      "Alba",
      "Arad",
      "Argeș",
      "Bacău",
      "Bihor",
      "Bistrița-Năsăud",
      "Botoșani",
      "Brașov",
      "Brăila",
      "Bucharest",
      "Buzău",
      "Caraș-Severin",
      "Călărași",
      "Cluj",
      "Constanța",
      "Covasna",
      "Dâmbovița",
      "Dolj",
      "Galați",
      "Giurgiu",
      "Gorj",
      "Harghita",
      "Hunedoara",
      "Ialomița",
      "Iași",
      "Ilfov",
      "Maramureș",
      "Mehedinți",
      "Mureș",
      "Neamț",
      "Olt",
      "Prahova",
      "Satu Mare",
      "Sălaj",
      "Sibiu",
      "Suceava",
      "Teleorman",
      "Timiș",
      "Tulcea",
      "Vaslui",
      "Vâlcea",
      "Vrancea",
    ],
  },
  {
    label: "Russia",
    value: "Russia",
    country: "Russia",
    states: [
      "Adygea",
      "Altai Krai",
      "Altai Republic",
      "Amur",
      "Arkhangelsk",
      "Astrakhan",
      "Bashkortostan",
      "Belgorod",
      "Bryansk",
      "Buryatia",
      "Chechen Republic",
      "Chelyabinsk",
      "Chukotka",
      "Chuvashia",
      "Dagestan",
      "Ingushetia",
      "Irkutsk",
      "Ivanovo",
      "Jewish Autonomous Oblast",
      "Kabardino-Balkaria",
      "Kaliningrad",
      "Kalmykia",
      "Kaluga",
      "Kamchatka",
      "Karachay-Cherkessia",
      "Karelia",
      "Kemerovo",
      "Khabarovsk",
      "Khakassia",
      "Khanty-Mansi",
      "Kirov",
      "Komi",
      "Kostroma",
      "Krasnodar",
      "Krasnoyarsk",
      "Kurgan",
      "Kursk",
      "Leningrad",
      "Lipetsk",
      "Magadan",
      "Mari El",
      "Mordovia",
      "Moscow",
      "Moscow Oblast",
      "Murmansk",
      "Nenets",
      "Nizhny Novgorod",
      "Novgorod",
      "Novosibirsk",
      "Omsk",
      "Orenburg",
      "Oryol",
      "Penza",
      "Perm",
      "Primorsky",
      "Pskov",
      "Rostov",
      "Ryazan",
      "Sakhalin",
      "Samara",
      "Saratov",
      "Smolensk",
      "Stavropol",
      "Sverdlovsk",
      "Tambov",
      "Tatarstan",
      "Tomsk",
      "Tula",
      "Tver",
      "Tyumen",
      "Udmurtia",
      "Ulyanovsk",
      "Vladimir",
      "Volgograd",
      "Vologda",
      "Voronezh",
      "Yamal-Nenets",
      "Yaroslavl",
      "Zabaykalsky",
    ],
  },
  {
    label: "Rwanda",
    value: "Rwanda",
    country: "Rwanda",
    states: [
      "Eastern Province",
      "Kigali",
      "Northern Province",
      "Southern Province",
      "Western Province",
    ],
  },
  {
    label: "Saint Kitts and Nevis",
    value: "Saint Kitts and Nevis",
    country: "Saint Kitts and Nevis",
    states: [
      "Christ Church Nichola Town",
      "Saint Anne Sandy Point",
      "Saint George Basseterre",
      "Saint George Gingerland",
      "Saint James Windward",
      "Saint John Capisterre",
      "Saint John Figtree",
      "Saint Mary Cayon",
      "Saint Paul Capisterre",
      "Saint Paul Charlestown",
      "Saint Peter Basseterre",
      "Saint Thomas Lowland",
      "Saint Thomas Middle Island",
      "Trinity Palmetto Point",
    ],
  },
  {
    label: "Saint Lucia",
    value: "Saint Lucia",
    country: "Saint Lucia",
    states: [
      "Anse la Raye",
      "Canaries",
      "Castries",
      "Choiseul",
      "Dennery",
      "Gros Islet",
      "Laborie",
      "Micoud",
      "Soufrière",
      "Vieux Fort",
    ],
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
    country: "Saint Vincent and the Grenadines",
    states: [
      "Charlotte",
      "Grenadines",
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint Patrick",
    ],
  },
  {
    label: "Samoa",
    value: "Samoa",
    country: "Samoa",
    states: [
      "A'ana",
      "Aiga-i-le-Tai",
      "Atua",
      "Fa'asaleleaga",
      "Gaga'emauga",
      "Gagaifomauga",
      "Palauli",
      "Satupa'itea",
      "Tuamasaga",
      "Va'a-o-Fonoti",
      "Vaisigano",
    ],
  },
  {
    label: "San Marino",
    value: "San Marino",
    country: "San Marino",
    states: [
      "Acquaviva",
      "Borgo Maggiore",
      "Chiesanuova",
      "Domagnano",
      "Faetano",
      "Fiorentino",
      "Montegiardino",
      "San Marino",
      "Serravalle",
    ],
  },
  {
    label: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
    country: "Sao Tome and Principe",
    states: [
      "Água Grande",
      "Cantagalo",
      "Caué",
      "Lemba",
      "Lobata",
      "Mé-Zóchi",
      "Príncipe",
    ],
  },
  {
    label: "Saudi Arabia",
    value: "Saudi Arabia",
    country: "Saudi Arabia",
    states: [
      "Al Bahah",
      "Al Jawf",
      "Al Madinah",
      "Al Qassim",
      "Ar Riyad",
      "Asir",
      "Eastern Province",
      "Ha'il",
      "Jazan",
      "Makkah",
      "Najran",
      "Northern Borders",
      "Tabuk",
    ],
  },
  {
    label: "Senegal",
    value: "Senegal",
    country: "Senegal",
    states: [
      "Dakar",
      "Diourbel",
      "Fatick",
      "Kaffrine",
      "Kaolack",
      "Kédougou",
      "Kolda",
      "Louga",
      "Matam",
      "Saint-Louis",
      "Sédhiou",
      "Tambacounda",
      "Thiès",
      "Ziguinchor",
    ],
  },
  {
    label: "Serbia",
    value: "Serbia",
    country: "Serbia",
    states: [
      "Belgrade",
      "Bor",
      "Braničevo",
      "Central Banat",
      "Danube",
      "Jablanica",
      "Kolubara",
      "Mačva",
      "Moravica",
      "Nišava",
      "North Bačka",
      "North Banat",
      "Pčinja",
      "Pirot",
      "Podunavlje",
      "Pomoravlje",
      "Rasina",
      "Raška",
      "South Bačka",
      "South Banat",
      "Srem",
      "Šumadija",
      "Toplica",
      "West Bačka",
      "Zaječar",
      "Zlatibor",
      "Kosovo and Metohija",
      "Vojvodina",
    ],
  },
  {
    label: "Seychelles",
    value: "Seychelles",
    country: "Seychelles",
    states: [
      "Anse aux Pins",
      "Anse Boileau",
      "Anse Etoile",
      "Anse Royale",
      "Au Cap",
      "Baie Lazare",
      "Baie Sainte Anne",
      "Beau Vallon",
      "Bel Air",
      "Bel Ombre",
      "Cascade",
      "Glacis",
      "Grand Anse Mahé",
      "Grand Anse Praslin",
      "La Digue",
      "La Rivière Anglaise",
      "Les Mamelles",
      "Mont Buxton",
      "Mont Fleuri",
      "Plaisance",
      "Pointe Larue",
      "Port Glaud",
      "Roche Caiman",
      "Saint Louis",
      "Takamaka",
    ],
  },
  {
    label: "Sierra Leone",
    value: "Sierra Leone",
    country: "Sierra Leone",
    states: [
      "Eastern Province",
      "Northern Province",
      "North Western Province",
      "Southern Province",
      "Western Area",
    ],
  },
  {
    label: "Singapore",
    value: "Singapore",
    country: "Singapore",
    states: [], // Singapore is a unitary state with no subdivisions
  },
  {
    label: "Slovakia",
    value: "Slovakia",
    country: "Slovakia",
    states: [
      "Banská Bystrica",
      "Bratislava",
      "Košice",
      "Nitra",
      "Prešov",
      "Trenčín",
      "Trnava",
      "Žilina",
    ],
  },
  {
    label: "Slovenia",
    value: "Slovenia",
    country: "Slovenia",
    states: [
      "Ajdovščina",
      "Beltinci",
      "Benedikt",
      "Bistrica ob Sotli",
      "Bled",
      "Bloke",
      "Bohinj",
      "Borovnica",
      "Bovec",
      "Braslovče",
      "Brda",
      "Brezovica",
      "Brežice",
      "Cankova",
      "Celje",
      "Cerklje na Gorenjskem",
      "Cerknica",
      "Cerkno",
      "Cerkvenjak",
      "Črenšovci",
      "Črna na Koroškem",
      "Črnomelj",
      "Destrnik",
      "Divača",
      "Dobje",
      "Dobrepolje",
      "Dobrova-Polhov Gradec",
      "Dobrovnik",
      "Dol pri Ljubljani",
      "Dolenjske Toplice",
      "Domžale",
      "Dornava",
      "Dravograd",
      "Duplek",
      "Gorenja Vas-Poljane",
      "Gorišnica",
      "Gorje",
      "Gornja Radgona",
      "Gornji Grad",
      "Gornji Petrovci",
      "Grad",
      "Grosuplje",
      "Hajdina",
      "Hoče-Slivnica",
      "Hodoš",
      "Horjul",
      "Hrastnik",
      "Hrpelje-Kozina",
      "Idrija",
      "Ig",
      "Ilirska Bistrica",
      "Ivančna Gorica",
      "Izola",
      "Jesenice",
      "Jezersko",
      "Juršinci",
      "Kamnik",
      "Kanal",
      "Kidričevo",
      "Kobarid",
      "Kobilje",
      "Kočevje",
      "Komen",
      "Komenda",
      "Koper",
      "Kostel",
      "Kozje",
      "Kranj",
      "Kranjska Gora",
      "Križevci",
      "Krško",
      "Kungota",
      "Kuzma",
      "Laško",
      "Lenart",
      "Lendava",
      "Litija",
      "Ljubljana",
      "Ljubno",
      "Ljutomer",
      "Log-Dragomer",
      "Logatec",
      "Loška Dolina",
      "Loški Potok",
      "Lovrenc na Pohorju",
      "Luče",
      "Lukovica",
      "Majšperk",
      "Makole",
      "Maribor",
      "Markovci",
      "Medvode",
      "Mengeš",
      "Metlika",
      "Mežica",
      "Miklavž na Dravskem Polju",
      "Miren-Kostanjevica",
      "Mirna",
      "Mirna Peč",
      "Mislinja",
      "Mokronog-Trebelno",
      "Moravče",
      "Moravske Toplice",
      "Mozirje",
      "Murska Sobota",
      "Muta",
      "Naklo",
      "Nazarje",
      "Nova Gorica",
      "Novo Mesto",
      "Odranci",
      "Oplotnica",
      "Ormož",
      "Osilnica",
      "Pesnica",
      "Piran",
      "Pivka",
      "Podčetrtek",
      "Podlehnik",
      "Podvelka",
      "Poljčane",
      "Polzela",
      "Postojna",
      "Prebold",
      "Preddvor",
      "Prevalje",
      "Ptuj",
      "Puconci",
      "Rače-Fram",
      "Radeče",
      "Radenci",
      "Radlje ob Dravi",
      "Radovljica",
      "Ravne na Koroškem",
      "Razkrižje",
      "Rečica ob Savinji",
      "Renče-Vogrsko",
      "Ribnica",
      "Ribnica na Pohorju",
      "Rogaška Slatina",
      "Rogašovci",
      "Rogatec",
      "Ruše",
      "Selnica ob Dravi",
      "Semič",
      "Sevnica",
      "Sežana",
      "Slovenj Gradec",
      "Slovenska Bistrica",
      "Slovenske Konjice",
      "Sodražica",
      "Solčava",
      "Starše",
      "Straža",
      "Sveta Ana",
      "Sveta Trojica v Slovenskih Goricah",
      "Sveti Andraž v Slovenskih Goricah",
      "Sveti Jurij ob Ščavnici",
      "Sveti Jurij v Slovenskih Goricah",
      "Sveti Tomaž",
      "Šalovci",
      "Šempeter-Vrtojba",
      "Šenčur",
      "Šentilj",
      "Šentjernej",
      "Šentjur",
      "Šentrupert",
      "Škocjan",
      "Škofja Loka",
      "Škofljica",
      "Šmarje pri Jelšah",
      "Šmarjeske Toplice",
      "Šmartno ob Paki",
      "Šmartno pri Litiji",
      "Šoštanj",
      "Štore",
      "Tabor",
      "Tišina",
      "Tolmin",
      "Trbovlje",
      "Trebnje",
      "Trnovska Vas",
      "Trzin",
      "Turnišče",
      "Velenje",
      "Velika Polana",
      "Velike Lašče",
      "Veržej",
      "Videm",
      "Vipava",
      "Vitanje",
      "Vodice",
      "Vojnik",
      "Vransko",
      "Vrhnika",
      "Vuzenica",
      "Zagorje ob Savi",
      "Zavrč",
      "Zreče",
      "Žalec",
      "Železniki",
      "Žetale",
      "Žiri",
      "Žirovnica",
      "Žužemberk",
    ],
  },
  {
    label: "Solomon Islands",
    value: "Solomon Islands",
    country: "Solomon Islands",
    states: [
      "Central",
      "Choiseul",
      "Guadalcanal",
      "Honiara",
      "Isabel",
      "Makira-Ulawa",
      "Malaita",
      "Rennell and Bellona",
      "Temotu",
      "Western",
    ],
  },
  {
    label: "Somalia",
    value: "Somalia",
    country: "Somalia",
    states: [
      "Awdal",
      "Bakool",
      "Banaadir",
      "Bari",
      "Bay",
      "Galguduud",
      "Gedo",
      "Hiiraan",
      "Jubbada Dhexe",
      "Jubbada Hoose",
      "Mudug",
      "Nugaal",
      "Sanaag",
      "Shabeellaha Dhexe",
      "Shabeellaha Hoose",
      "Sool",
      "Togdheer",
      "Woqooyi Galbeed",
    ],
  },
  {
    label: "South Africa",
    value: "South Africa",
    country: "South Africa",
    states: [
      "Eastern Cape",
      "Free State",
      "Gauteng",
      "KwaZulu-Natal",
      "Limpopo",
      "Mpumalanga",
      "North West",
      "Northern Cape",
      "Western Cape",
    ],
  },
  {
    label: "South Korea",
    value: "South Korea",
    country: "South Korea",
    states: [
      "Busan",
      "Chungcheongbuk-do",
      "Chungcheongnam-do",
      "Daegu",
      "Daejeon",
      "Gangwon-do",
      "Gwangju",
      "Gyeonggi-do",
      "Gyeongsangbuk-do",
      "Gyeongsangnam-do",
      "Incheon",
      "Jeju",
      "Jeollabuk-do",
      "Jeollanam-do",
      "Seoul",
      "Ulsan",
    ],
  },
  {
    label: "South Sudan",
    value: "South Sudan",
    country: "South Sudan",
    states: [
      "Central Equatoria",
      "Eastern Equatoria",
      "Jonglei",
      "Lakes",
      "Northern Bahr el Ghazal",
      "Unity",
      "Upper Nile",
      "Warrap",
      "Western Bahr el Ghazal",
      "Western Equatoria",
    ],
  },
  {
    label: "Spain",
    value: "Spain",
    country: "Spain",
    states: [
      "Andalusia",
      "Aragon",
      "Asturias",
      "Balearic Islands",
      "Basque Country",
      "Canary Islands",
      "Cantabria",
      "Castile and León",
      "Castilla-La Mancha",
      "Catalonia",
      "Community of Madrid",
      "Extremadura",
      "Galicia",
      "La Rioja",
      "Navarre",
      "Region of Murcia",
      "Valencian Community",
    ],
  },
  {
    label: "Sri Lanka",
    value: "Sri Lanka",
    country: "Sri Lanka",
    states: [
      "Central Province",
      "Eastern Province",
      "North Central Province",
      "Northern Province",
      "North Western Province",
      "Sabaragamuwa Province",
      "Southern Province",
      "Uva Province",
      "Western Province",
    ],
  },
  {
    label: "Sudan",
    value: "Sudan",
    country: "Sudan",
    states: [
      "Al Jazirah",
      "Al Qadarif",
      "Blue Nile",
      "Central Darfur",
      "East Darfur",
      "Kassala",
      "Khartoum",
      "North Darfur",
      "North Kordofan",
      "Northern",
      "Red Sea",
      "River Nile",
      "Sennar",
      "South Darfur",
      "South Kordofan",
      "West Darfur",
      "West Kordofan",
      "White Nile",
    ],
  },
  {
    label: "Suriname",
    value: "Suriname",
    country: "Suriname",
    states: [
      "Brokopondo",
      "Commewijne",
      "Coronie",
      "Marowijne",
      "Nickerie",
      "Para",
      "Paramaribo",
      "Saramacca",
      "Sipaliwini",
      "Wanica",
    ],
  },
  {
    label: "Sweden",
    value: "Sweden",
    country: "Sweden",
    states: [
      "Blekinge",
      "Dalarna",
      "Gävleborg",
      "Gotland",
      "Halland",
      "Jämtland",
      "Jönköping",
      "Kalmar",
      "Kronoberg",
      "Norrbotten",
      "Örebro",
      "Östergötland",
      "Skåne",
      "Södermanland",
      "Stockholm",
      "Uppsala",
      "Värmland",
      "Västerbotten",
      "Västernorrland",
      "Västmanland",
      "Västra Götaland",
    ],
  },
  {
    label: "Switzerland",
    value: "Switzerland",
    country: "Switzerland",
    states: [
      "Aargau",
      "Appenzell Ausserrhoden",
      "Appenzell Innerrhoden",
      "Basel-Landschaft",
      "Basel-Stadt",
      "Bern",
      "Fribourg",
      "Geneva",
      "Glarus",
      "Graubünden",
      "Jura",
      "Lucerne",
      "Neuchâtel",
      "Nidwalden",
      "Obwalden",
      "Schaffhausen",
      "Schwyz",
      "Solothurn",
      "St. Gallen",
      "Thurgau",
      "Ticino",
      "Uri",
      "Valais",
      "Vaud",
      "Zug",
      "Zurich",
    ],
  },
  {
    label: "Syria",
    value: "Syria",
    country: "Syria",
    states: [
      "Al-Hasakah",
      "Al-Raqqah",
      "Aleppo",
      "As-Suwayda",
      "Damascus",
      "Daraa",
      "Deir ez-Zor",
      "Hama",
      "Homs",
      "Idlib",
      "Latakia",
      "Quneitra",
      "Rif Dimashq",
      "Tartus",
    ],
  },
  {
    label: "Taiwan",
    value: "Taiwan",
    country: "Taiwan",
    states: [
      "Changhua",
      "Chiayi",
      "Hsinchu",
      "Hualien",
      "Kaohsiung",
      "Keelung",
      "Kinmen",
      "Lienchiang",
      "Miaoli",
      "Nantou",
      "New Taipei",
      "Penghu",
      "Pingtung",
      "Taichung",
      "Tainan",
      "Taipei",
      "Taitung",
      "Taoyuan",
      "Yilan",
      "Yunlin",
    ],
  },
  {
    label: "Tajikistan",
    value: "Tajikistan",
    country: "Tajikistan",
    states: ["Dushanbe", "Gorno-Badakhshan", "Khatlon", "Sughd"],
  },
  {
    label: "Tanzania",
    value: "Tanzania",
    country: "Tanzania",
    states: [
      "Arusha",
      "Dar es Salaam",
      "Dodoma",
      "Geita",
      "Iringa",
      "Kagera",
      "Katavi",
      "Kigoma",
      "Kilimanjaro",
      "Lindi",
      "Manyara",
      "Mara",
      "Mbeya",
      "Mjini Magharibi",
      "Morogoro",
      "Mtwara",
      "Mwanza",
      "Njombe",
      "Pemba North",
      "Pemba South",
      "Pwani",
      "Rukwa",
      "Ruvuma",
      "Shinyanga",
      "Simiyu",
      "Singida",
      "Songwe",
      "Tabora",
      "Tanga",
      "Unguja North",
      "Unguja South",
    ],
  },
  {
    label: "Thailand",
    value: "Thailand",
    country: "Thailand",
    states: [
      "Amnat Charoen",
      "Ang Thong",
      "Bangkok",
      "Bueng Kan",
      "Buri Ram",
      "Chachoengsao",
      "Chai Nat",
      "Chaiyaphum",
      "Chanthaburi",
      "Chiang Mai",
      "Chiang Rai",
      "Chon Buri",
      "Chumphon",
      "Kalasin",
      "Kamphaeng Phet",
      "Kanchanaburi",
      "Khon Kaen",
      "Krabi",
      "Lampang",
      "Lamphun",
      "Loei",
      "Lop Buri",
      "Mae Hong Son",
      "Maha Sarakham",
      "Mukdahan",
      "Nakhon Nayok",
      "Nakhon Pathom",
      "Nakhon Phanom",
      "Nakhon Ratchasima",
      "Nakhon Sawan",
      "Nakhon Si Thammarat",
      "Nan",
      "Narathiwat",
      "Nong Bua Lam Phu",
      "Nong Khai",
      "Nonthaburi",
      "Pathum Thani",
      "Pattani",
      "Phang Nga",
      "Phatthalung",
      "Phayao",
      "Phetchabun",
      "Phetchaburi",
      "Phichit",
      "Phitsanulok",
      "Phra Nakhon Si Ayutthaya",
      "Phrae",
      "Phuket",
      "Prachin Buri",
      "Prachuap Khiri Khan",
      "Ranong",
      "Ratchaburi",
      "Rayong",
      "Roi Et",
      "Sa Kaeo",
      "Sakon Nakhon",
      "Samut Prakan",
      "Samut Sakhon",
      "Samut Songkhram",
      "Saraburi",
      "Satun",
      "Si Sa Ket",
      "Sing Buri",
      "Songkhla",
      "Sukhothai",
      "Suphan Buri",
      "Surat Thani",
      "Surin",
      "Tak",
      "Trang",
      "Trat",
      "Ubon Ratchathani",
      "Udon Thani",
      "Uthai Thani",
      "Uttaradit",
      "Yala",
      "Yasothon",
    ],
  },
  {
    label: "Timor-Leste",
    value: "Timor-Leste",
    country: "Timor-Leste",
    states: [
      "Aileu",
      "Ainaro",
      "Baucau",
      "Bobonaro",
      "Cova Lima",
      "Dili",
      "Ermera",
      "Lautém",
      "Liquiçá",
      "Manatuto",
      "Manufahi",
      "Viqueque",
      "Oecusse",
    ],
  },
  {
    label: "Togo",
    value: "Togo",
    country: "Togo",
    states: ["Centrale", "Kara", "Maritime", "Plateaux", "Savanes"],
  },
  {
    label: "Tonga",
    value: "Tonga",
    country: "Tonga",
    states: ["Eua", "Ha'apai", "Niuas", "Tongatapu", "Vava'u"],
  },
  {
    label: "Trinidad and Tobago",
    value: "Trinidad and Tobago",
    country: "Trinidad and Tobago",
    states: [
      "Arima",
      "Chaguanas",
      "Couva-Tabaquite-Talparo",
      "Diego Martin",
      "Mayaro-Rio Claro",
      "Penal-Debe",
      "Point Fortin",
      "Port of Spain",
      "Princes Town",
      "San Fernando",
      "San Juan-Laventille",
      "Sangre Grande",
      "Siparia",
      "Tunapuna-Piarco",
      "Tobago",
    ],
  },
  {
    label: "Tunisia",
    value: "Tunisia",
    country: "Tunisia",
    states: [
      "Ariana",
      "Béja",
      "Ben Arous",
      "Bizerte",
      "Gabès",
      "Gafsa",
      "Jendouba",
      "Kairouan",
      "Kasserine",
      "Kébili",
      "Kef",
      "Mahdia",
      "Manouba",
      "Medenine",
      "Monastir",
      "Nabeul",
      "Sfax",
      "Sidi Bouzid",
      "Siliana",
      "Sousse",
      "Tataouine",
      "Tozeur",
      "Tunis",
      "Zaghouan",
    ],
  },
  {
    label: "Turkey",
    value: "Turkey",
    country: "Turkey",
    states: [
      "Adana",
      "Adıyaman",
      "Afyonkarahisar",
      "Ağrı",
      "Aksaray",
      "Amasya",
      "Ankara",
      "Antalya",
      "Ardahan",
      "Artvin",
      "Aydın",
      "Balıkesir",
      "Bartın",
      "Batman",
      "Bayburt",
      "Bilecik",
      "Bingöl",
      "Bitlis",
      "Bolu",
      "Burdur",
      "Bursa",
      "Çanakkale",
      "Çankırı",
      "Çorum",
      "Denizli",
      "Diyarbakır",
      "Düzce",
      "Edirne",
      "Elazığ",
      "Erzincan",
      "Erzurum",
      "Eskişehir",
      "Gaziantep",
      "Giresun",
      "Gümüşhane",
      "Hakkari",
      "Hatay",
      "Iğdır",
      "Isparta",
      "Istanbul",
      "İzmir",
      "Kahramanmaraş",
      "Karabük",
      "Karaman",
      "Kars",
      "Kastamonu",
      "Kayseri",
      "Kilis",
      "Kırıkkale",
      "Kırklareli",
      "Kırşehir",
      "Kocaeli",
      "Konya",
      "Kütahya",
      "Malatya",
      "Manisa",
      "Mardin",
      "Mersin",
      "Muğla",
      "Muş",
      "Nevşehir",
      "Niğde",
      "Ordu",
      "Osmaniye",
      "Rize",
      "Sakarya",
      "Samsun",
      "Şanlıurfa",
      "Siirt",
      "Sinop",
      "Şırnak",
      "Sivas",
      "Tekirdağ",
      "Tokat",
      "Trabzon",
      "Tunceli",
      "Uşak",
      "Van",
      "Yalova",
      "Yozgat",
      "Zonguldak",
    ],
  },
  {
    label: "Turkmenistan",
    value: "Turkmenistan",
    country: "Turkmenistan",
    states: ["Ahal", "Balkan", "Dashoguz", "Lebap", "Mary", "Ashgabat"],
  },
  {
    label: "Tuvalu",
    value: "Tuvalu",
    country: "Tuvalu",
    states: [
      "Funafuti",
      "Nanumaga",
      "Nanumea",
      "Niutao",
      "Nui",
      "Nukufetau",
      "Nukulaelae",
      "Vaitupu",
    ],
  },
  {
    label: "Uganda",
    value: "Uganda",
    country: "Uganda",
    states: [
      "Abim",
      "Adjumani",
      "Amolatar",
      "Amuria",
      "Amuru",
      "Apac",
      "Arua",
      "Budaka",
      "Bududa",
      "Bugiri",
      "Bugweri",
      "Bukedea",
      "Bukomansimbi",
      "Bukwo",
      "Bulambuli",
      "Buliisa",
      "Bundibugyo",
      "Bunyangabu",
      "Bushenyi",
      "Busia",
      "Butaleja",
      "Butebo",
      "Buvuma",
      "Buyende",
      "Dokolo",
      "Gomba",
      "Gulu",
      "Hoima",
      "Ibanda",
      "Iganga",
      "Isingiro",
      "Jinja",
      "Kaabong",
      "Kabale",
      "Kabarole",
      "Kaberamaido",
      "Kagadi",
      "Kakumiro",
      "Kalangala",
      "Kaliro",
      "Kalungu",
      "Kampala",
      "Kamuli",
      "Kamwenge",
      "Kanungu",
      "Kapchorwa",
      "Kasese",
      "Katakwi",
      "Kayunga",
      "Kibaale",
      "Kiboga",
      "Kibuku",
      "Kiruhura",
      "Kiryandongo",
      "Kisoro",
      "Kitgum",
      "Koboko",
      "Kole",
      "Kotido",
      "Kumi",
      "Kwania",
      "Kween",
      "Kyankwanzi",
      "Kyegegwa",
      "Kyotera",
      "Lamwo",
      "Lira",
      "Luuka",
      "Luwero",
      "Lwengo",
      "Lyantonde",
      "Manafwa",
      "Maracha",
      "Masaka",
      "Masindi",
      "Mayuge",
      "Mbale",
      "Mbarara",
      "Mitooma",
      "Mityana",
      "Moroto",
      "Moyo",
      "Mpigi",
      "Mubende",
      "Mukono",
      "Namisindwa",
      "Namutumba",
      "Napak",
      "Nebbi",
      "Ngora",
      "Ntoroko",
      "Ntungamo",
      "Nwoya",
      "Omoro",
      "Otuke",
      "Oyam",
      "Pader",
      "Pakwach",
      "Pallisa",
      "Rakai",
      "Rubanda",
      "Rubirizi",
      "Rukiga",
      "Rukungiri",
      "Sembabule",
      "Serere",
      "Sheema",
      "Sironko",
      "Soroti",
      "Tororo",
      "Wakiso",
      "Yumbe",
      "Zombo",
    ],
  },
  {
    label: "Ukraine",
    value: "Ukraine",
    country: "Ukraine",
    states: [
      "Cherkasy",
      "Chernihiv",
      "Chernivtsi",
      "Dnipropetrovsk",
      "Donetsk",
      "Ivano-Frankivsk",
      "Kharkiv",
      "Kherson",
      "Khmelnytskyi",
      "Kirovohrad",
      "Kyiv",
      "Luhansk",
      "Lviv",
      "Mykolaiv",
      "Odessa",
      "Poltava",
      "Rivne",
      "Sumy",
      "Ternopil",
      "Vinnytsia",
      "Volyn",
      "Zakarpattia",
      "Zaporizhzhia",
      "Zhytomyr",
      "Crimea",
    ],
  },
  {
    label: "United Arab Emirates",
    value: "United Arab Emirates",
    country: "United Arab Emirates",
    states: [
      "Abu Dhabi",
      "Ajman",
      "Dubai",
      "Fujairah",
      "Ras al-Khaimah",
      "Sharjah",
      "Umm al-Quwain",
    ],
  },
  {
    label: "United Kingdom",
    value: "United Kingdom",
    country: "United Kingdom",
    states: ["England", "Scotland", "Wales", "Northern Ireland"],
  },
  {
    label: "United States",
    value: "United States",
    country: "United States",
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
      "District of Columbia",
    ],
  },
  {
    label: "Uruguay",
    value: "Uruguay",
    country: "Uruguay",
    states: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Río Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ],
  },
  {
    label: "Uzbekistan",
    value: "Uzbekistan",
    country: "Uzbekistan",
    states: [
      "Andijan",
      "Bukhara",
      "Fergana",
      "Jizzakh",
      "Karakalpakstan",
      "Namangan",
      "Navoiy",
      "Qashqadaryo",
      "Samarqand",
      "Sirdaryo",
      "Surxondaryo",
      "Tashkent",
      "Xorazm",
    ],
  },
  {
    label: "Vanuatu",
    value: "Vanuatu",
    country: "Vanuatu",
    states: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"],
  },
  {
    label: "Vatican City",
    value: "Vatican City",
    country: "Vatican City",
    states: [], // Vatican City is a unitary state with no subdivisions
  },
  {
    label: "Venezuela",
    value: "Venezuela",
    country: "Venezuela",
    states: [
      "Amazonas",
      "Anzoátegui",
      "Apure",
      "Aragua",
      "Barinas",
      "Bolívar",
      "Carabobo",
      "Cojedes",
      "Delta Amacuro",
      "Falcón",
      "Guárico",
      "Lara",
      "Mérida",
      "Miranda",
      "Monagas",
      "Nueva Esparta",
      "Portuguesa",
      "Sucre",
      "Táchira",
      "Trujillo",
      "Vargas",
      "Yaracuy",
      "Zulia",
      "Federal Dependencies",
      "Capital District",
    ],
  },
  {
    label: "Vietnam",
    value: "Vietnam",
    country: "Vietnam",
    states: [
      "An Giang",
      "Bà Rịa-Vũng Tàu",
      "Bạc Liêu",
      "Bắc Giang",
      "Bắc Kạn",
      "Bắc Ninh",
      "Bến Tre",
      "Bình Định",
      "Bình Dương",
      "Bình Phước",
      "Bình Thuận",
      "Cà Mau",
      "Cao Bằng",
      "Đắk Lắk",
      "Đắk Nông",
      "Điện Biên",
      "Đồng Nai",
      "Đồng Tháp",
      "Gia Lai",
      "Hà Giang",
      "Hà Nam",
      "Hà Tĩnh",
      "Hải Dương",
      "Hậu Giang",
      "Hòa Bình",
      "Hưng Yên",
      "Khánh Hòa",
      "Kiên Giang",
      "Kon Tum",
      "Lai Châu",
      "Lâm Đồng",
      "Lạng Sơn",
      "Lào Cai",
      "Long An",
      "Nam Định",
      "Nghệ An",
      "Ninh Bình",
      "Ninh Thuận",
      "Phú Thọ",
      "Phú Yên",
      "Quảng Bình",
      "Quảng Nam",
      "Quảng Ngãi",
      "Quảng Ninh",
      "Quảng Trị",
      "Sóc Trăng",
      "Sơn La",
      "Tây Ninh",
      "Thái Bình",
      "Thái Nguyên",
      "Thanh Hóa",
      "Thừa Thiên Huế",
      "Tiền Giang",
      "Trà Vinh",
      "Tuyên Quang",
      "Vĩnh Long",
      "Vĩnh Phúc",
      "Yên Bái",
      "Cần Thơ",
      "Đà Nẵng",
      "Hải Phòng",
      "Hà Nội",
      "Hồ Chí Minh City",
    ],
  },
  {
    label: "Yemen",
    value: "Yemen",
    country: "Yemen",
    states: [
      "Abyan",
      "Aden",
      "Al Bayda",
      "Al Hudaydah",
      "Al Jawf",
      "Al Mahrah",
      "Al Mahwit",
      "Amanat Al Asimah",
      "Dhamar",
      "Hadramaut",
      "Hajjah",
      "Ibb",
      "Lahij",
      "Marib",
      "Raymah",
      "Sa'ada",
      "Sana'a",
      "Shabwah",
      "Socotra",
      "Ta'izz",
    ],
  },
  {
    label: "Zambia",
    value: "Zambia",
    country: "Zambia",
    states: [
      "Central",
      "Copperbelt",
      "Eastern",
      "Luapula",
      "Lusaka",
      "Muchinga",
      "Northern",
      "North-Western",
      "Southern",
      "Western",
    ],
  },
  {
    label: "Zimbabwe",
    value: "Zimbabwe",
    country: "Zimbabwe",
    states: [
      "Bulawayo",
      "Harare",
      "Manicaland",
      "Mashonaland Central",
      "Mashonaland East",
      "Mashonaland West",
      "Masvingo",
      "Matabeleland North",
      "Matabeleland South",
      "Midlands",
    ],
  },
];
