export const quantityMetrics = [
  { label: "Bag", value: "Bag" },
  { label: "Bale", value: "Bale" },
  { label: "Bar", value: "Bar" },
  { label: "Block", value: "Block" },
  { label: "Board", value: "Board" },
  { label: "Bottle", value: "Bottle" },
  { label: "Box", value: "Box" },
  { label: "Bucket", value: "Bucket" },
  { label: "Bundle", value: "Bundle" },
  { label: "Can", value: "Can" },
  { label: "Carton", value: "Carton" },
  { label: "Case", value: "Case" },
  { label: "Coil", value: "Coil" },
  { label: "Container", value: "Container" },
  { label: "Crate", value: "Crate" },
  { label: "Cubic Foot", value: "Cubic Foot" },
  { label: "Cubic Meter", value: "Cubic Meter" },
  { label: "Dozen", value: "Dozen" },
  { label: "Drum", value: "Drum" },
  { label: "Foot", value: "Foot" },
  { label: "Gallon", value: "Gallon" },
  { label: "Gram", value: "Gram" },
  { label: "Kilogram", value: "Kilogram" },
  { label: "Liter", value: "Liter" },
  { label: "Meter", value: "Meter" },
  { label: "Milliliter", value: "Milliliter" },
  { label: "Millimeter", value: "Millimeter" },
  { label: "Pack", value: "Pack" },
  { label: "Packet", value: "Packet" },
  { label: "Pair", value: "Pair" },
  { label: "Pallet", value: "Pallet" },
  { label: "Piece", value: "Piece" },
  { label: "Pipe Length", value: "Pipe Length" },
  { label: "Ream", value: "Ream" },
  { label: "Reel", value: "Reel" },
  { label: "Roll", value: "Roll" },
  { label: "Roller", value: "Roller" },
  { label: "Rod", value: "Rod" },
  { label: "Sack", value: "Sack" },
  { label: "Set", value: "Set" },
  { label: "Sheet", value: "Sheet" },
  { label: "Square Foot", value: "Square Foot" },
  { label: "Square Meter", value: "Square Meter" },
  { label: "Stick", value: "Stick" },
  { label: "Tank", value: "Tank" },
  { label: "Ton", value: "Ton" },
  { label: "Tube", value: "Tube" },
  { label: "Unit", value: "Unit" },
  { label: "Yard", value: "Yard" },
];
