export const routes = {
  home: "/",
  joinExpert: "/become-expert",
  congrats: "/become-expert/congratulations",
  postJob: "/post-job",
  postMaterial: "/post-material",
  cart: "/cart",
  checkout: "/checkout",
  postMaterialCongrats: "/post-material/congratulations",
  marketplace: {
    jobs: "/marketplace/jobs",
    jobInfo: (jobId: string) => `/marketplace/jobs/${jobId}`,
    experts: "/marketplace/experts",
    expertInfo: (expertId: string) => `/marketplace/experts/${expertId}`,
    materials: "/marketplace/materials",
    materialInfo: (materialId: string) =>
      `/marketplace/materials/${materialId}`,
    materialInfoReviews: (materialId: string) =>
      `/marketplace/materials/${materialId}/reviews`,
  },
  profile: (userId: string) => `/profile/${userId}`,
  login: "/auth/login",
  signUp: "/auth/register",
  verifyEmail: "/auth/verify-email",

  dashboard: "/dashboard/overview",
  dashboardLinks: {
    marketplace: "/dashboard/marketplace",
    payments: "/dashboard/payments",
    jobs: "/dashboard/jobs",
    reports: "/dashboard/reports",
    messages: "/dashboard/messages",
    support: "/dashboard/support",
  },
  enterprise: {
    bookService: "/enterprise/book-service",
    bookMaintenance: "/enterprise/book-maintenance",
    bookMeeting: "/enterprise/book-meeting",
    success: "/enterprise/success",
  },

  aboutUs: "/about-us",
  policy: "/policy",
  terms: "/terms",
  cookiePolicy: "/cookie-policy",
  how: "/how-it-works",
  faq: "/faq",
  guides: "/guides",
  helpCenter: "/help-center",
  blog: "/blog",
  news: "/news",
  tips: "/tips",
  testimonial: "/testimonial",
  completeProfile: "/dashboard/profile/complete",
};
