export const productCategories = [
  { label: "Building Materials", value: "building materials" },
  { label: "Cement & Concrete", value: "cement & concrete" },
  { label: "Bricks & Blocks", value: "bricks & blocks" },
  { label: "Sand & Aggregates", value: "sand & aggregates" },
  { label: "Steel & Iron", value: "steel & iron" },
  { label: "Roofing Materials", value: "roofing materials" },
  { label: "Doors", value: "doors" },
  { label: "Windows", value: "windows" },
  { label: "Flooring", value: "flooring" },
  { label: "Tiles", value: "tiles" },
  { label: "Ceilings", value: "ceilings" },
  { label: "Paints & Coatings", value: "paints & coatings" },
  { label: "Plumbing Supplies", value: "plumbing supplies" },
  { label: "Bathroom Fixtures", value: "bathroom fixtures" },
  { label: "Kitchen Fixtures", value: "kitchen fixtures" },
  { label: "Electrical Supplies", value: "electrical supplies" },
  { label: "Lighting", value: "lighting" },
  { label: "Solar & Renewable Energy", value: "solar & renewable energy" },
  { label: "HVAC & Ventilation", value: "hvac & ventilation" },
  { label: "Home Appliances", value: "home appliances" },
  { label: "Furniture", value: "furniture" },
  { label: "Interior Decor", value: "interior decor" },
  { label: "Smart Home Devices", value: "smart home devices" },
  { label: "Security Systems", value: "security systems" },
  { label: "Tools & Equipment", value: "tools & equipment" },
  { label: "Power Tools", value: "power tools" },
  { label: "Hand Tools", value: "hand tools" },
  { label: "Safety Equipment", value: "safety equipment" },
  { label: "Scaffolding & Ladders", value: "scaffolding & ladders" },
  { label: "Heavy Machinery", value: "heavy machinery" },
  { label: "Generators", value: "generators" },
  { label: "Water Tanks", value: "water tanks" },
  { label: "Borehole Equipment", value: "borehole equipment" },
  { label: "Fencing & Gates", value: "fencing & gates" },
  { label: "Glass & Aluminium", value: "glass & aluminium" },
  { label: "Wood & Timber", value: "wood & timber" },
  { label: "Plywood & Boards", value: "plywood & boards" },
  { label: "Landscaping Materials", value: "landscaping materials" },
  { label: "Gardening Supplies", value: "gardening supplies" },
  { label: "Cleaning Supplies", value: "cleaning supplies" },
  { label: "Office Supplies", value: "office supplies" },
  { label: "Packaging Materials", value: "packaging materials" },
  { label: "Industrial Supplies", value: "industrial supplies" },
  { label: "Construction Chemicals", value: "construction chemicals" },
  { label: "Fasteners & Hardware", value: "fasteners & hardware" },
  { label: "Waterproofing Materials", value: "waterproofing materials" },
  { label: "Insulation Materials", value: "insulation materials" },
  { label: "Welding Materials", value: "welding materials" },
  {
    label: "Road & Civil Construction Materials",
    value: "road & civil construction materials",
  },
  { label: "Other", value: "other" },
];
