import { ChartReportData, ReportTargets, ReportTab } from "../types";

export const reportTabs: { value: ReportTab; label: string }[] = [
  { value: "jobs", label: "Jobs" },
  { value: "finance", label: "Finance" },
  { value: "trade", label: "Trade" },
  { value: "insights", label: "Insights" },
];

export const chartReports: ChartReportData[] = [
  {
    id: "jobs",
    tab: "jobs",
    title: "Jobs",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "13",
    centerLabel: "Jobs",
    segments: [
      { label: "Active", value: 8, color: "#138A46" },
      { label: "Pending", value: 3, color: "#FF9933" },
      { label: "Completed", value: 2, color: "#D8D8D8" },
      { label: "Overdue", value: 0.2, color: "#FF5D7A" },
    ],
    legends: [
      { label: "Active", value: "8", color: "#138A46" },
      { label: "Pending", value: "3", color: "#FF9933" },
      { label: "Completed", value: "2", color: "#D8D8D8" },
      { label: "Overdue", value: "0", color: "#FF5D7A" },
    ],
    actionLabel: "Manage Jobs",
  },
  {
    id: "applications",
    tab: "jobs",
    title: "Applications",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "800",
    centerLabel: "Applicants",
    segments: [
      { label: "Applicants", value: 62, color: "#E7E7E7" },
      { label: "Hired", value: 5, color: "#8EA2FF" },
      { label: "Re-hired", value: 28, color: "#6667FF" },
      { label: "Flagged", value: 5, color: "#FF5D7A" },
    ],
    legends: [
      { label: "Applicants", value: "800", color: "#E7E7E7" },
      { label: "Hired", value: "3", color: "#8EA2FF" },
      { label: "Re-hired", value: "2", color: "#6667FF" },
      { label: "Flagged", value: "0", color: "#FF5D7A" },
    ],
    views: [
      {
        value: "applicants",
        label: "Applicants",
        centerValue: "800",
        centerLabel: "Applicants",
        segments: [
          { label: "Applicants", value: 62, color: "#E7E7E7" },
          { label: "Hired", value: 5, color: "#8EA2FF" },
          { label: "Re-hired", value: 28, color: "#6667FF" },
          { label: "Flagged", value: 5, color: "#FF5D7A" },
        ],
        legends: [
          { label: "Applicants", value: "800", color: "#E7E7E7" },
          { label: "Hired", value: "3", color: "#8EA2FF" },
          { label: "Re-hired", value: "2", color: "#6667FF" },
          { label: "Flagged", value: "0", color: "#FF5D7A" },
        ],
      },
      {
        value: "my-applications",
        label: "My Applications",
        centerValue: "24",
        centerLabel: "Applications",
        segments: [
          { label: "Submitted", value: 50, color: "#E7E7E7" },
          { label: "Shortlisted", value: 25, color: "#8EA2FF" },
          { label: "Accepted", value: 17, color: "#6667FF" },
          { label: "Declined", value: 8, color: "#FF5D7A" },
        ],
        legends: [
          { label: "Submitted", value: "24", color: "#E7E7E7" },
          { label: "Shortlisted", value: "6", color: "#8EA2FF" },
          { label: "Accepted", value: "4", color: "#6667FF" },
          { label: "Declined", value: "2", color: "#FF5D7A" },
        ],
      },
    ],
  },
  {
    id: "earnings",
    tab: "finance",
    title: "Earnings",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "₦ 150,000",
    centerLabel: "Earned",
    currencyOptions: ["NGN", "USD", "EUR", "CAD"],
    segments: [
      { label: "Jobs", value: 85, color: "#18A154" },
      { label: "Materials", value: 35, color: "#B7F88B" },
      { label: "Referrals", value: 30, color: "#B8F2CF" },
      { label: "Others", value: 0.2, color: "#E5E7E6" },
    ],
    legends: [
      { label: "Jobs", value: "₦ 85k", color: "#18A154" },
      { label: "Materials", value: "₦ 35k", color: "#B7F88B" },
      { label: "Referrals", value: "₦ 30k", color: "#B8F2CF" },
      { label: "Others", value: "₦ 0", color: "#E5E7E6" },
    ],
  },
  {
    id: "expenses",
    tab: "finance",
    title: "Expenses",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "₦ 150,000",
    centerLabel: "Spent",
    currencyOptions: ["NGN", "USD", "EUR", "CAD"],
    segments: [
      { label: "Jobs", value: 85, color: "#FF5D7A" },
      { label: "Materials", value: 35, color: "#FFDDE3" },
      { label: "Promotions", value: 30, color: "#FFC4CE" },
      { label: "Others", value: 0.2, color: "#FFF0F3" },
    ],
    legends: [
      { label: "Jobs", value: "₦ 85k", color: "#FF5D7A" },
      { label: "Materials", value: "₦ 35k", color: "#FFC4CE" },
      { label: "Promotions", value: "₦ 30k", color: "#FFDDE3" },
      { label: "Others", value: "₦ 0", color: "#FFF0F3" },
    ],
  },
  {
    id: "orders",
    tab: "trade",
    title: "Orders",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "19",
    centerLabel: "Orders",
    segments: [
      { label: "Completed", value: 14, color: "#138A46" },
      { label: "Pending", value: 2, color: "#B7F88B" },
      { label: "Cancelled", value: 2, color: "#E7E7E7" },
      { label: "Returned", value: 1, color: "#FF5D7A" },
    ],
    legends: [
      { label: "Completed", value: "14", color: "#138A46" },
      { label: "Pending", value: "2", color: "#B7F88B" },
      { label: "Cancelled", value: "2", color: "#E7E7E7" },
      { label: "Returned", value: "1", color: "#FF5D7A" },
    ],
    actionLabel: "Manage Orders",
  },
  {
    id: "sales",
    tab: "trade",
    title: "Sales",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "Last 30 days",
    centerValue: "49",
    centerLabel: "Sales",
    segments: [
      { label: "Completed", value: 40, color: "#138A46" },
      { label: "Ongoing", value: 5, color: "#B7F88B" },
      { label: "Cancelled", value: 2, color: "#E7E7E7" },
      { label: "Returned", value: 2, color: "#FF5D7A" },
    ],
    legends: [
      { label: "Completed", value: "40", color: "#138A46" },
      { label: "Ongoing", value: "5", color: "#B7F88B" },
      { label: "Cancelled", value: "2", color: "#E7E7E7" },
      { label: "Returned", value: "2", color: "#FF5D7A" },
    ],
    actionLabel: "Manage Listed Items",
  },
  {
    id: "overview",
    tab: "insights",
    title: "Overview",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "2026",
    centerValue: "15.3K",
    centerLabel: "Impressions",
    segments: [
      { label: "Reach", value: 8, color: "#18A154" },
      { label: "Saves", value: 3, color: "#B7F88B" },
      { label: "Shares", value: 2, color: "#83E7AB" },
      { label: "Clicks", value: 0.5, color: "#D7F8E4" },
      { label: "Contacts", value: 2, color: "#D8D8D8" },
    ],
    legends: [
      { label: "Reach", value: "8", color: "#18A154" },
      { label: "Saves", value: "3", color: "#B7F88B" },
      { label: "Shares", value: "2", color: "#83E7AB" },
      { label: "Clicks", value: "0", color: "#D7F8E4" },
      { label: "Contacts", value: "2", color: "#D8D8D8" },
    ],
  },
  {
    id: "promotion",
    tab: "insights",
    title: "Promotion Duration",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "2026",
    centerValue: "7 days",
    centerLabel: "remaining",
    segments: [
      { label: "Remaining", value: 23, color: "#FF5D7A" },
      { label: "Used", value: 7, color: "#F0F1F1" },
    ],
    legends: [
      { label: "Promotion Duration", value: "30 days", color: "#FF5D7A" },
    ],
    actionLabel: "+ Increase Limits",
  },
  {
    id: "clicks",
    tab: "insights",
    title: "Clicks",
    subtitle: "From 1-31 March, 2026",
    periodLabel: "2026",
    centerValue: "650 clicks",
    centerLabel: "remaining",
    segments: [
      { label: "Remaining", value: 650, color: "#FF9933" },
      { label: "Used", value: 1350, color: "#F0F1F1" },
    ],
    legends: [
      { label: "Total Clicks", value: "2000", color: "#FF9933" },
    ],
    actionLabel: "+ Increase Limits",
  },
];

export const defaultReportTargets: ReportTargets = {
  duration: "monthly",
  referralsMade: "15",
  friendsInvited: "24",
  jobsDone: "2",
  amountEarned: "150000",
};
